"""Close source reuse contract and atomically supply exact files to existing inbox."""
from pathlib import Path
import json,hashlib,subprocess,base64,numpy as np
L=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');R=B/'c-mug-existing-grasp-reader-r1';O=B/'c-mug-existing-grasp-handoff-r1';E=L/'evidence/c-mug-existing-grasp-handoff-r1';E.mkdir(exist_ok=False)
read=lambda p:json.loads(Path(p).read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();write=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
m=read(R/'MUG_GRASP_CONSUMER_MANIFEST_R1.json');raw=read(R/'NativeGraspLocalTRS169.json');channels=read(R/'NativeGraspBody169.json')['channels'];assert len(channels)==294 and len(raw['frames'])==169
for fn,x in m['files'].items():assert sha(x['path'])==x['SHA']
guard=B/'o1-c-mug-existing-grasp-reader-r1/NATIVE_GUARD_RESULT.json';assert read(guard)['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN'
left=[c for c in channels if '.L"' in c['path'] and any(c['path'].startswith('pose.bones["'+n) for n in ['index','middle','ring','pinky','thumb'])];v=np.array([[k['value'] for k in c['keys']] for c in left]);assert len(left)==105
assert np.array_equal(v[:,68:118],np.repeat(v[:,68,None],50,axis=1))
assert all(k['value']==c['keys'][0]['value'] for c in channels if '.R"' in c['path'] for k in c['keys'])
stage=[('OPEN_REACH',1,51),('CLOSE_HANDLE',52,69),('LIFT_CLOSED',69,85),('STATIC_HOLD',85,101),('LOWER_CLOSED',102,119),('OPEN_RELEASE',119,136),('RETURN_OPEN',136,169)]
events={'attach_candidate_frame':69,'attach_seconds':68/24,'hold_anchor_frame':85,'static_hold_frames':[85,101],'release_candidate_frame':119,'release_seconds':118/24,'fully_open_frame':136,'event_basis':'Inferred authored timing, not embedded animation events. Runtime owner chooses attach/release and verifies actual mug/socket continuity. Frame102 is lowering start while fingers stay closed; earlier raw recommended_release_start102 is superseded.'}
anchor={'parent_rig':'Meshy_Fitted_Rig','bone':'hand.L','bone_local_palm_midpoint':raw['frames'][84]['hands']['L']['palmMidpointHandLocal'],'grasp69':raw['frames'][68]['hands']['L'],'hold85':raw['frames'][84]['hands']['L'],'release119':raw['frames'][118]['hands']['L'],'precision':'Provisional half-hand-bone +Y point and hand orientation; not measured mug handle fit/contact or force support. Use current imported hand.L bone-local socket; convert by existing H reflection exactly once.'}
private={'source_SHA':m['source_SHA'],'source_action_SHA':m['source_action_SHA'],'library_SHA':'a2808d19d71cf55165b35b3bebcf752eebad8d76f5f4d6018c8b9a7435a8aeb2','actions':m['actions'],'fps':24,'frame_range':[1,169],'stages':[{'name':n,'frames':[a,b],'seconds':[(a-1)/24,(b-1)/24]} for n,a,b in stage],'events':events,'anchor':anchor,'basis_runtime_recipe':'Reuse Talk native Channel/Key parser. BODY29442upper/digit bones. Unity q=(x,-y,-z,w); location H=(-x,y,z); localRotation=importedRestRotation*q; localPosition=restPosition+restMatrix.MultiplyVector(location); original localScale. Parent-local TRS samples are Blender native reference, not Unity-ready values. No animated lower/root.','ownership':'One BODY writer, one shared source clock, head/hair transports single root ownership. FACE/gaze original owner preserved. Pause/resume under existing physical ownership. World object/root gameplay belongs existing writer.','quality':'Tier-C source-only/TierP0; actual MUG contact and finger/webbing/thumb fidelity PASS2 HOLD; no new motion'}
write(O/'C_MUG_GRASP_HANDOFF_PRIVATE_R1.json',private)
# Exact receiver paths were absent in bounded prior inbox/Downloads/product-input checks.
opts=['-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=8','-i','C:/Users/JAEWAN/.ssh/id_ed25519_laptop'];target='zeros@192.168.0.16'
def remote(script):
 p="[Console]::OutputEncoding=[Text.UTF8Encoding]::new(); $ProgressPreference='SilentlyContinue'; "+script;r=subprocess.run(['ssh',*opts,target,'powershell.exe','-NoProfile','-NonInteractive','-EncodedCommand',base64.b64encode(p.encode('utf-16le')).decode()],capture_output=True,text=True,encoding='utf8',errors='replace',timeout=60);assert r.returncode==0,r.stderr[-1500:];return json.loads(r.stdout.lstrip('\ufeff').strip())
folder='C:/YuriTransfer/inbox/ROOT_PM_C_MUG_GRASP_R1';files=[B/'YURI_R4_NATIVE_GRASP_SOURCE_ONLY_R1_20261005.zip',*sorted(R.glob('*.json')),O/'C_MUG_GRASP_HANDOFF_PRIVATE_R1.json'];receipts=[]
assert sha(files[0])=='9d23f40e7ebdb812edd939eed61fd017427d4ba02bdadcd88d5bffcc43bc74ec'
for p in files:
 dest=folder+'/'+p.name;expected=sha(p);size=p.stat().st_size
 pre=remote("$p='"+dest+"'; if(Test-Path -LiteralPath $p){@{exists=$true;hostname=$env:COMPUTERNAME;path=$p;SHA=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLower();bytes=(Get-Item -LiteralPath $p).Length}}else{@{exists=$false;hostname=$env:COMPUTERNAME}}|ConvertTo-Json -Compress")
 assert pre['hostname']=='DESKTOP-11NSABR'
 if pre['exists']:assert pre['SHA']==expected and pre['bytes']==size;receipts.append({**pre,'copied':False});continue
 remote("New-Item -ItemType Directory -Path '"+folder+"' -Force|Out-Null; @{ready=$true}|ConvertTo-Json -Compress")
 partial=dest+'.partial';cp=subprocess.run(['scp',*opts,str(p),target+':'+partial],capture_output=True,text=True,timeout=120);assert cp.returncode==0,cp.stderr[-1500:]
 post=remote("$p='"+partial+"';$s=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLower();$b=(Get-Item -LiteralPath $p).Length;if($s -ne '"+expected+"' -or $b -ne "+str(size)+"){throw 'SHA/size mismatch'};if(Test-Path -LiteralPath '"+dest+"'){throw 'No overwrite'};Move-Item -LiteralPath $p -Destination '"+dest+"';@{hostname=$env:COMPUTERNAME;path='"+dest+"';SHA=$s;bytes=$b}|ConvertTo-Json -Compress");receipts.append({**post,'copied':True})
write(O/'C_MUG_RECEIVER_CUSTODY_R1.json',{'scope':'ROOT_PM_C_MUG_SOURCE_HANDOFF_R1','receiver_files':receipts,'prior_checks':'Exact names absent from C:/YuriTransfer,Downloads,product artifacts and Assets; bounded locations only, not global absence proof. Earlier already_received flag was not independently verified and is superseded by this receipt.','new_archive_export_framework':False,'product_repo_changed':False})
scalar={'source_SHA':m['source_SHA'],'source_action_SHA':m['source_action_SHA'],'library_SHA':private['library_SHA'],'actions':m['actions'],'stages':private['stages'],'events':events,'hand':'LEFT','right_hand_static':True,'body_channels':294,'upper_digit_bones':42,'fps':24,'frame_range':[1,169],'original81_OFF_signature_exact':True,'source_candidate_bytes_unchanged':True,'guard_status':read(guard)['guard_status'],'guard_SHA':sha(guard),'private_handoff':str(O/'C_MUG_GRASP_HANDOFF_PRIVATE_R1.json'),'private_handoff_SHA':sha(O/'C_MUG_GRASP_HANDOFF_PRIVATE_R1.json'),'receiver_files':receipts,'TierP':0,'PASS2_debt':'Finger/webbing/thumb/contact/prop fit/precision','new_motion':False,'product_modified':False,'runtime_consumer':'Existing native Talk reader/ApplyBodyBone; rest+basis reflection, one clock/writer; product import receipt still pending'}
write(E/'C_MUG_GRASP_SOURCE_HANDOFF_SCALAR_R1.json',scalar)
report='''# C MUG 기존 Grasp 재사용 handoff — 2026-10-05

새 motion 후보 없이 원본 Grasp 재사용만 완료했다. 활성 손은 hand.L; 오른손 채널/손목은 정지. BODY42 upper/digit bones294채널, HEAD/HAIR transport 두 Action을 기존 Talk native reader schema로 제공한다. R4/source81 OFF signature와 source/candidate bytes 동일, strict guard terminal PASS. 새 render/baseline/6Reaction/contact precision 검사는0.

24fps1..169/7초 key interval: open reach1–51, close52–69, lift closed69–85, exact full pose hold85–101, lower closed102–119, open release119–136, return open136–169. LEFT fingers exact closed plateau69–118. 이벤트는 authored data에서 추론한 integration 후보: attach69(2.833초), hold85(3.5초), release119(4.917초), fully-open136(5.625초). 처음 raw sampler의 release102 제안은 손을 낮추는 시작을 release로 오인했으므로 consumer handoff에서119로 교정했다. 102에서는 손가락이 닫힌 상태다.

Anchor는 hand.L local +Y 반 bone 길이의 provisional palm midpoint 및 해당 손 orientation이다. 실제 MUG handle fitting/penetration/contact/force proof 아님. 제품 writer가 실제 handle socket을 이 지점에 맞추고 attach/release/ownership/resume를 구현한다. 기존 source upper tracks에는 lower/root navigation이 없다. imported rest+basis/H reflection을 기존 consumer 방식으로 한 번 적용하며 parent-local Blender TRS를 Unity local 값으로 직접 복사하지 않는다.

기존 ZIP9d23f40e/librarya2808d19를 재생성하지 않았다. 예전 already_received 표시는 수신 파일 위치를 독립 검증하지 않은 것이었다. 이번 bounded inbox/Downloads/Assets/artifacts exact-name 검사는 없음을 보였고, 기존 zeros/SSH 경로로 새 inbox scope에 닫힌 ZIP 및 JSON만 전달해 각 receiver SHA/bytes 검증했다. 전역 파일 부재 증명은 아니다. 정확한 수신 위치/해시는 scalar JSON 참조; 새 archive/exporter/framework/제품 코드 변경0. Tier-C source-only/TierP0. finger/webbing/thumb/handle contact/fidelity는 PASS2 debt이며 Unity gameplay PASS는 해당 writer의 실제 receipt가 필요하다.
'''
(E/'YURI_R4_C_MUG_EXISTING_GRASP_HANDOFF_R1_KO.md').write_text(report,encoding='utf8')
p=L/'CODEX_HANDOFF_KO.md';p.write_text('# 2026-10-05 C MUG existing Grasp input\n\n새motion0/source81 OFF preserved. LEFT42upper/digit294channels/native169@24. attach69/hold85–101/lower102/release119/open136/return169. Closed9d23packet+a280library와 existing-native consumer JSON을 exact receiver SHA 검증. Provisional palm midpoint/actualMUGcontact PASS2 HOLD. report evidence/c-mug-existing-grasp-handoff-r1/YURI_R4_C_MUG_EXISTING_GRASP_HANDOFF_R1_KO.md.\n\n'+p.read_text(encoding='utf8'),encoding='utf8')
x=read(L/'LATEST_RUN.json');x['c_mug_existing_grasp_handoff_r1']={'report':str(E/'YURI_R4_C_MUG_EXISTING_GRASP_HANDOFF_R1_KO.md'),'receiver_folder':folder,'source_SHA':m['source_SHA'],'hand':'LEFT','attach_frame':69,'release_frame':119,'new_motion':False,'TierP':0};write(L/'LATEST_RUN.json',x)
print(json.dumps({'status':'C_MUG_EXISTING_SOURCE_HANDOFF_READY','receiver_folder':folder,'files':len(receipts),'new_motion':False}))
