"""Sanitized manifest: facts, bounded observations and unresolved fields separate."""
from pathlib import Path
import json,re,hashlib,cv2,numpy as np
R=Path(__file__).resolve().parents[1];E=R/'evidence/dance-benchmark-r1';L=R/'local/dance-benchmark-r1';p=E/'reference_manifest.json';d=json.loads(p.read_text());d['duplicate_frame_diagnostic_10_to_20s'].pop('mean_abs_gray_changes',None)
cap=cv2.VideoCapture(str(L/'reference/reference.mp4'));cap.set(cv2.CAP_PROP_POS_FRAMES,1200);anchors=[]
for k in range(360):
    ok,f=cap.read();assert ok;g=cv2.cvtColor(f,cv2.COLOR_BGR2GRAY);profile=np.abs(np.diff(g[20:140].astype(float),axis=1)).mean(0);anchors.append([400+int(np.argmax(profile[400:570])),1300+int(np.argmax(profile[1300:1450]))])
cap.release();anchor=np.array(anchors);audio=json.loads((E/'audio_reference_analysis.json').read_text());log=(L/'full_scene_scan.log').read_text(errors='replace');cuts=re.findall(r'pts_time:([\d.]+)',log)
d.update({'dancer_selection':{'appearance':'white layered dress, rightmost through20–26s; no identity attribution','track':'single fixed ROI1380,100,1840,1020, reviewed across every0.5s and full interval playback','identity_switch':'none observed','dancers_observed':5},'dance_start_seconds':0.,'dance_end_seconds':207.616667,'dance_interval_definition':'visible performance, including opening and closing held choreography poses; no title card or outro removed','dynamic_movement_onset_estimate_seconds':2.25,'dynamic_movement_onset_uncertainty_seconds':.25,'final_pose_reached_estimate_seconds':206.,'final_pose_reached_uncertainty_seconds':.5,'boundary_scope':'pose onset/settling are visual estimates from timecoded contacts, not frame-exact manual annotations','camera_motion':{'whole_reference':'framing/pan/zoom changes; later ceiling and side-wall coverage changes. Physical-camera vs digital reframing not distinguishable from this view','benchmark_interval':[20,26],'selected_static_background_gate':{'frames':360,'two_wall_seam_peak_to_peak_px':np.ptp(anchor,axis=0).tolist(),'studio_floor_edge_2hz_px':843,'floor_edge_peak_to_peak_selected_2hz_px':0},'camera_estimation_scope':'background2D anchors verified for selected segment; rejected affine ECC; no estimated6DOF world camera or known intrinsics'},'cuts':{'whole_reference_scan':'FFmpeg scene filter at native60fps after480x270 resize','threshold':.20,'cut_candidates_seconds':[float(x) for x in cuts],'hard_cut_verdict':'none detected at this threshold; continuously changing framing remains, not a universal static-camera assumption'},'floor_and_feet':{'selected_segment':'full body and shoes visible for target; skirt hides hip centres; wrists can overlap torso/hair or nearby performer','whole_reference':'group formation occludes some dancers; floor/feet generally visible in overview, no all-frame whole-dance visibility certification'},'root_motion_selected':{'pelvis_lateral_image_range_px':{'mediapipe':110.838,'rtmw3d':107.813},'normalized_lateral_range_assumed_m':{'mediapipe':.241,'rtmw3d':.258},'world_depth_and_metric_scale':'UNRESOLVED: assumed actor height1.65m and focal1700px, no known camera/body/floor calibration'},'repeated_or_chorus_intervals':{'audio_template':[20,26],'strongest_repeat_candidate':[91.6,97.6],'chroma_similarity':.9673258876,'other_candidates':audio['repeated_audio_candidates'],'chorus_labels':'not verified; audio recurrence candidates are not counted as annotated choruses'},'first_benchmark':{'source_interval':[20,26],'motion_fps':60,'frames':360,'preview_fps':30,'expanded_phrase_or_chorus':False,'reason':'exclude framing change beginning after26s; accurate-motion gate not passed'},'status':'REFERENCE_ANALYSIS_CHECKPOINT_WITH_LABELLED_BOUNDARY_CHORUS_AND_WORLD_CALIBRATION_LIMITS'})
p.write_text(json.dumps(d,indent=2));(E/'full_scene_scan_receipt.json').write_text(json.dumps({'source_sha256':d['source_sha256'],'frames_scanned':12457,'native_fps':60,'analysis_resolution':[480,270],'threshold':.20,'cut_candidate_times_seconds':[float(x) for x in cuts],'log_sha256':hashlib.sha256((L/'full_scene_scan.log').read_bytes()).hexdigest(),'command':'ffmpeg -threads4 -i reference.mp4 -an -vf scale=480:270,select=gt(scene,0.20),showinfo -f null NUL'},indent=2));print('REFERENCE_FINALIZED',len(cuts),np.ptp(anchor,axis=0).tolist())
