"""Publish compact scalar findings, distinguishing unassigned envelope from no envelope."""
from pathlib import Path
import json,hashlib
L=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'dots-r2-readonly-custody-r1/DOTS_R2_READONLY_CUSTODY_PRIVATE_R1.json';m=json.loads(P.read_bytes());a=m['candidate_inventory'];E=L/'evidence/dots-r2-readonly-custody-r1';E.mkdir(exist_ok=True)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
g=B/'o1-dots-r2-readonly-custody-r1/NATIVE_GUARD_RESULT.json';assert json.loads(g.read_bytes())['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN'
env=[x for x in a['envelopes'] if 'MUG_ThumbVolume' in x['path']];assert len(env)==1 and env[0]['key_count']==169 and env[0]['min']==0 and env[0]['max']==1
assert all(x['default_value']==0 and x['shape_action'] is None and x['shape_drivers']==0 and x['nla_tracks']==0 for x in a['correctives'])
scalar={'scope':'ONE read-only audit / nonblocking PASS2','candidate_SHA':m['candidate_SHA'],'candidate_bytes':m['candidate_bytes'],'source_bytes_unchanged':True,'cold_reopen_same_file_full_snapshot_exact':True,'default_OFF':True,'frame':a['frame'],'fps':a['fps'],'objects':a['objects'],'bones':a['bones'],'materials':a['materials'],'actions_count':len(a['actions']),'rigs':a['rigs'],'same_file_domain_hashes_only':a['domain_hashes'],'correctives':a['correctives'],'corrective_envelope_unassigned':env[0],'envelope_scope':'FCurve numeric inspection only; no ON geometry/playback test','vertex_count_note':'Upstream declares165 support vertices; saved effective nonzero Basis deltas164 per inspected mesh. Cause not established.','original_object_rig_rest_bind_weights_actions_preservation':'UNKNOWN: appropriate Dots study control40fa19/pristine16440ac absent from bounded local Root artifacts and Desktop research outputs. Same-file reopen does not establish source parity.','canonical_R4_equivalence':'NOT_ASSERTED; distinct derived Dots study','contact_visual_Unity_TierP':'HOLD; no new render/contact/ON/Unity tests','guard_status':'PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN','guard_SHA':sha(g),'private_receipt':str(P),'private_receipt_SHA':sha(P),'new_candidate_save_export_product_edit':False,'TierP':0}
write(E/'DOTS_R2_CUSTODY_SCALAR_R1.json',scalar)
write(E/'REPORTING_CORRECTION_R1.json',{'initial_closure_assertion':'Incorrectly assumed absence of corrective envelope because no key Action is assigned. Closure assertion stopped publication. Native audit itself had passed.','correction':'Complete native inventory contains MUG_CORRECTIVE_R2_Envelope_Unassigned_OFF with169keys,0..1, default unassigned. Corrected report distinguishes existing envelope from active binding. No second native job/new candidate.','original_reader_commit':'f08ee5b26f73bf2d483c0745a955a6fb1d98e6e2'})
report='''# Dots R2 custody-only audit — 2026-10-05

Scoped custody PASS / source preservation UNKNOWN / quality HOLD. Candidate SHA67fd96b796ea510644c7c65549f410d4e277f04db91b1c57c991b430245904dc,31630511B. One CPU-only strict owned job opened the same file twice, never saved; full snapshots identical and input byte SHA unchanged. Frame1/24fps,110objects/137bones/21materials/112Actions. BODY and QA inspection corrective values0, key Action/driver/NLA absent: default OFF confirmed.

Envelope exists separately as MUG_CORRECTIVE_R2_Envelope_Unassigned_OFF,169keys1..169, sampled range0..1. Values at1/49/136/169=0,69/85/101=1,119=.994999468. It remains unassigned. Numeric FCurve inspection does not establish ON evaluated geometry or playback acceptance. The initial reporting assertion mistook unassigned for absent; preserved correction record, no native rerun.

Stored Basis delta effective nonzero vertices164 per inspected mesh, versus upstream declared165 authored support vertices; discrepancy recorded without inventing a cause. Max object-world delta1.399999mm, mesh-local2.61682mm. These are stored shape deltas, not posed volume/contact proof.

Appropriate Dots mug control40fa19e9 and pristine master16440ac6 are absent from bounded local review/research paths. Original-object/rig/rest/bind/weights/Actions preservation to that baseline is UNKNOWN. Upstream receipts are attributed claims; same-file reopening cannot replace direct control comparison. Derived Dots source is not asserted equal to immutable canonical R4a30fc. Source/canonical overwrite, export, Unity and new candidate0.

Remaining mug/handle/otherfinger penetration and visual/temporal quality are PASS2 HOLD/nonblocking. No final promotion/TierP/F2/F3 or PASS1 prerequisite. Next required evidence for source parity is the exact Dots control/master bytes, not another thumb candidate.
'''
(E/'YURI_DOTS_R2_CUSTODY_ONLY_R1_KO.md').write_text(report,encoding='utf8')
p=L/'CODEX_HANDOFF_KO.md';p.write_text('# 2026-10-05 Dots R2 custody-only / nonblocking PASS2\n\n67fd96 candidate cold reopen/defaultOFF PASS. Existing unassigned169key0..1 envelope numerically inspected. Original parity UNKNOWN(control40fa19/pristine16440ac unavailable);164effective versus165reported/maxobject-world1.4mm. ON/contact/runtime HOLD. No R4equivalence/newcandidate/save/export/Unity. evidence/dots-r2-readonly-custody-r1/YURI_DOTS_R2_CUSTODY_ONLY_R1_KO.md.\n\n'+p.read_text(encoding='utf8'),encoding='utf8')
x=json.loads((L/'LATEST_RUN.json').read_bytes());x['dots_r2_custody_only_r1']={'report':str(E/'YURI_DOTS_R2_CUSTODY_ONLY_R1_KO.md'),'candidate_SHA':m['candidate_SHA'],'custody':'SCOPED_PASS','source_parity':'UNKNOWN','contact_quality':'HOLD','nonblocking_PASS2':True,'TierP':0};write(L/'LATEST_RUN.json',x)
print('ONE_DOTS_AUDIT_CLOSED_CUSTODY_PASS_SOURCE_UNKNOWN_QUALITY_HOLD')
