"""Publish honest local lab receipt after the finite validation jobs finish."""
from pathlib import Path
import json, subprocess, hashlib, shutil, time
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'local/output'
validation=json.loads((ROOT/'evidence/export_validation.json').read_text(encoding='utf-8'))
assert validation['status']=='PASS'
probe=json.loads((ROOT/'evidence/comfy_cpu_probe.json').read_text(encoding='utf-8'))
assert probe['status']=='CPU_CORE_API_PASS' and probe['owned_probe_process_stopped']
mp4=OUT/'greeting_wave__proxy_previs.mp4'
media=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_entries','stream=codec_name,width,height,r_frame_rate,nb_frames','-show_entries','format=duration,size','-of','json',str(mp4)],text=True))
assert float(media['format']['duration'])==4 and media['streams'][0]['nb_frames']=='48'
(ROOT/'evidence/reel_ffprobe.json').write_text(json.dumps(media,indent=2)+'\n',encoding='utf-8')

def put(name,obj):
    (ROOT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

put('LATEST_RUN.json',{'run_id':'yuri-performance-r1-20261002','time_utc':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'workspace':str(ROOT.parents[1]),'latest_run_directory':str(OUT),'blender_file':str(OUT/'YURI_PERFORMANCE_PROXY_R1.blend'),'preview_video':str(mp4),'files':[{'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(OUT.glob('*')) if p.is_file() and p.suffix in {'.blend','.glb','.mp4','.png'}],'result':'LAB_PREPARATION_AND_PROXY_PIPELINE_VERIFIED','approved_actual_yuri_performances':0,'long_running_codex_worker_started':False})
put('catalog/higgsfield_shots.json',{'status':'DRAFTS_ONLY_NOT_SUBMITTED','verified_mcp_model_on_2026_10_02':'cinematic_studio_3_0','web_ui_version_is_not_mcp_model_id':True,'paid_submissions':0,'free_quota_used':0,'default_duration_seconds':4,'required_inputs_before_submit':['approved adult original character start image','same shot previz as motion reference only where selected model supports video input','current model schema and credit estimate','owner generation approval'],'shots':[{'id':'wave_A01','prompt':'Exactly one adult original anime-style woman, alone in a quiet cozy room. She notices a friend just beside the camera, makes a small relaxed greeting wave, then lets the hand settle while holding a warm smile. Gentle anticipation, one readable gesture, soft asymmetry, no abrupt pose reset. One continuous waist-up three-quarter shot, hands remain visible. No second performer, mirror duplicate, crowd or background person. Preserve the approved reference character and outfit.'},{'id':'shy_A01','prompt':'Exactly one adult original anime-style woman, alone. She meets the friend\'s gaze briefly, shows a restrained smile, glances away in embarrassment, holds a short pause, and looks back with a softer smile. Keep the head motion small and eyes coherent. One continuous close-medium shot. Preserve reference identity, natural eyelids and stable mouth. No extra person, abrupt camera move or exaggerated head wobble.'},{'id':'please_A01','prompt':'Exactly one adult original anime-style woman asks her friend a playful gentle favor through acting. A small preparatory pause, a modest head tilt, softly raised inner brows, slight forward attention, a hopeful smile, then a relaxed return. Adult character, affectionate nonsexual tone. One continuous medium shot, no extra hands or additional people. Preserve the same camera axis and reference identity.'}]})
(ROOT/'STUDY_PLAN_KO.md').write_text('''# 영상·연기 연구를 실제 자산으로 남기는 순서\n\n## 1. 두 결과물을 분리한다\n게임용 결과물은 bone motion, facial curves, gaze targets, contact windows, entry/exit pose, interruption markers다. 영상용 결과물은 previz/RGB/first-last/depth/pose/mask/camera metadata와 편집된 MP4다. MP4를 재사용 가능한 3D 모션으로 세지 않는다. 생성영상에서 움직임을 복원하는 경우 별도 추정·리타겟·접촉·얼굴 정리 실험으로 기록한다.\n\n## 2. 연기부터\n첫 3개는 인사, 수줍음, 부탁이다. 각 연기의 이유, 바라보는 상대, 감정 정점, 여운, 복귀가 읽혀야 한다. 자연형과 애니형은 각각 타이밍·포즈·표정 한계를 캘리브레이션하고 전 채널을 같은 비율로 키우지 않는다. 웃음은 mouthSmile 하나가 아니라 눈·눈썹·볼·입꼬리·턱과 머리/어깨 흐름을 함께 검수한다. 눈과 손이 클로즈업에서 버텨야 한다.\n\n## 3. 구도 실험\n같은 연기를 전신, 허리 위 3/4, 얼굴 클로즈업으로 비교한다. 카메라 위치·센서 폭·렌즈·피사체 거리를 함께 저장한다. 전신은 머리·발끝 여백, 애교는 얼굴과 손 silhouette, 시선은 상대방 위치를 검수한다. 세로 영상은 가로 crop이 아니라 별도 프레이밍으로 검증한다. 유리룸 플레이 중 카메라를 강제로 바꾸지 않는다.\n\n## 4. 프리비즈 패스\n각 샷에 beauty, previz.mp4, first/last frame, depth, pose, ID mask, camera metadata를 연결한다. 현재 R1에서 실제 생성한 패스는 proxy beauty/프리비즈/카메라다. Depth/OpenPose/ID는 아직 생성하지 않았고 빈 manifest 값을 완료로 간주하지 않는다. Blender depth의 거리 단위/정규화, pose의 키포인트 규약과 occlusion, mask의 객체 ID를 각 소비 모델과 맞춘 뒤 사용한다.\n\n## 5. ComfyUI\n현재 설치와 과거 성공 workflow를 유지한다. CPU API 재검증과 실제 GPU 영상 생성은 구분한다. Wan TI2V-5B I2V는 시작 프레임 실험 후보. pose/depth 강제는 별도의 Fun Control 등 모델이 필요하다. 관련 core 노드가 있어도 weights가 있다는 뜻은 아니다. 16GB GPU는 resolution/frame/activation/host RAM/decode까지 전체 과정으로 측정한다.\nH3는 과거 기술적 8/8 영상 성공과 스타일 실패, 이후 1인→3인 증식이 기록되어 있다. 단일 인물·고정 identity·시작 이미지 조건을 먼저 통제한다. 이 R1에서 GPU inference 및 신규 모델 설치는 하지 않았다.\n\n## 6. Higgsfield\n좋은 표정·카메라·타이밍 후보 또는 최종 영상 픽셀 제작을 맡긴다. Blender가 canonical 데이터 원본이다. 웹의 Cinema Studio 기능 이름과 MCP 모델 ID는 구분한다. 현재 MCP로 읽은 모델은 Cinema Studio Video 3.0이며 웹 문서의 4.0 기능을 동일 API에 임의로 전달하지 않는다. 실험은 동일 원화·동일 행동·동일 길이의 한 샷 A/B부터.\n\n## 7. 편집·오디오\n검증용 MP4는 CPU libx264를 썼다. 기존 NVENC API 불일치 기록 때문에 GPU encoder 준비 완료로 말하지 않는다. 후속은 first/middle/last frame 검사→전체 재생→샷 연결→자막→음량/음성 동기→최종 규격이다. 기존 video-motion-production-skills/Remotion 자산을 재사용한다. 음성 합성/보이스 선택·비용은 따로 확인한다. Audio-to-face는 speech/emotion 입력을 얼굴 곡선으로 옮기는 보조 경로이며 리깅/몸연기/시선 전체를 대신하지 않는다.\n\n## 8. 유리룸 도입\n현재 제품 브랜치의 실제 rig mapping과 runtime adapter를 확인한다. GLB bone+weights 수치 PASS만으로 VRM/Unity/Three.js 런타임 PASS라고 하지 않는다. 동일 캐릭터 round-trip 후 seated/standing 혼합, 컵 들고 중단, 스프링본 중복, mouth override, 저사양 프레임 예산까지 통과한 클립만 제품 라이브러리에 넣는다.\n\n## 실험 기록 템플릿\n질문/가설, source hashes·라이선스, 고정 변수, 바꾼 변수 1개, frame range·fps·카메라, 타이밍곡선, first-middle-last 및 MP4, 구조 검증/눈·입·손·접촉·구도 판정, RAM/VRAM/시간/비용, 실패 원인, 다음 실험 1개를 남긴다. 완료된 연기만 완료 수로 세고 계획·파생 조합·스키마 항목 수는 따로 쓴다.\n''',encoding='utf-8')
(ROOT/'README_KO.md').write_text('''# Yuri Performance / Previs Lab R1\n\n2026-10-02. 유리룸용 연기 자산과 영상 제작을 병행 준비하는 격리 연구 작업공간.\n정본 저장소: zeroslove-ai/video-production-skills\n브랜치: research/yuri-performance-previs-r1-20261002\n기존 제품/아바타 worktree, main, 노트북 Codex는 변경하지 않았다.\n\n## 실제로 완료한 것\n- 48종 모션 제작 계획 JSON: signature 12, conversation 12, room 12, continuity 12. 계획 수이며 제작 완료 48개가 아니다.\n- 16종 표정 의미 레시피, 자연형/애니형 프로파일, 눈/입/시선 충돌 해결 순서. 실제 캐릭터 대응은 미검증.\n- 렌즈/위치/센서/해상도가 있는 6개 카메라와 샷 manifest.\n- Blender 5.2.1 LTS에서 원본 절차형 proxy: 17 bones, 6 morph controls, 3개 타임라인 연기 seed, 3개 GLB.\n- GLB별 skin과 실제로 변화하는 rotation/weights 곡선, 시간 0 시작, 길이, 유한 수치, 끝의 기본 자세 복귀를 검증. 캐릭터 재타깃은 미검증.\n- CPU Cycles 프리뷰와 4초 384x216 12fps H.264 MP4 1개. 이는 Blender 렌더 시험이며 AI 영상 생성 결과가 아니다.\n- ComfyUI 0.34.6 / Python 3.12.10 / Torch 2.10.0+cu130: 격리 CPU API 시험 PASS, core 639 nodes, /system_stats 및 /queue 확인. 검증 프로세스 종료. 기본 서비스는 켜 두지 않았다.\n- 재현 스크립트, 숫자 QA, 실제 경로·해시, 코덱스 작업지시서와 영상 연구 계획.\n\n## 완료하지 않았거나 실행하지 않은 것\n- 실제 유리 얼굴 리깅, 손가락/눈꺼풀/입/혀·시선 고급 연기, 실제 유리룸 런타임 도입은 아직 아니다.\n- proxy에는 원래 해부학적 얼굴 topology/눈동자 리그/손가락이 없다. 예쁜 최종 캐릭터나 애교 품질로 평가한 산출물이 아니다.\n- live Blender MCP add-on 상태 조회는 보안 상태 판정 문제로 차단되어 이번 세션 live 연결 PASS로 처리하지 않았다. 별도 headless Blender 제작은 검증했다.\n- C:/YuriEmbodiedLab/runtime/gpu-lease.json의 PRODUCT_EXCLUSIVE 기록을 변경하지 않았다. 과거 PID는 조회 시 보이지 않았지만 자동 해제하지 않았다. 이번 GPU 영상 inference 0회.\n- Higgsfield 과금/무료 quota 사용, 새 대형 model 다운로드, ComfyUI 업데이트/partner node 실행 0회.\n- Depth/OpenPose/ID 패스와 최종 유리 리타겟, 음성 동기, cloud A/B는 후속 항목.\n- 장기 Codex worker, 예약 실행 또는 24시간 루프를 새로 시작하지 않았다.\n\n## 먼저 볼 파일\n`CODEX_HANDOFF_KO.md` → `STUDY_PLAN_KO.md` → `catalog/motions.json` → `catalog/face_recipes.json` → `LATEST_RUN.json`.\n판정 증거는 `evidence/comfy_cpu_probe.json`, `evidence/blender_proxy_build.json`, `evidence/export_validation.json`, `evidence/reel_ffprobe.json`.\n\n## 실행/열기\n`OPEN_OUTPUTS.cmd`는 산출물 폴더만 연다. Blender 원본과 GLB, preview PNG, proxy MP4의 절대경로는 `LATEST_RUN.json`에 있다.\n`RUN_CPU_PROBE.cmd`는 모델 추론 없는 격리 ComfyUI 검사 후 자신이 띄운 프로세스를 종료한다.\n`RUN_PROXY_PREVIS.cmd`는 원본 proxy를 다시 만들고 검증/인코딩한다. 기존 사용자 아바타는 읽거나 쓰지 않는다.\n\n## 다음 실제 제작 단위\n승인된 실제 아바타를 고정한 뒤 인사/수줍은 시선/부탁 3종부터 몸·얼굴·시선을 연결한다. 3종의 클로즈업과 복귀/중단 품질을 먼저 보고 12→48종으로 늘린다. GPU 예약이 미해결이어도 CPU authoring과 얼굴 mapping/QA는 계속 가능한 별도 작업이다.\n''',encoding='utf-8')
(ROOT/'SOURCES.md').write_text('''# Source snapshots reviewed 2026-10-02\n\n- Blender glTF bone/morph animation: https://docs.blender.org/manual/en/latest/addons/scene_gltf2.html\n- Blender shape keys: https://docs.blender.org/manual/en/latest/animation/shape_keys/introduction.html\n- Comfy Wan2.2: https://docs.comfy.org/tutorials/video/wan/wan2_2\n- Comfy Fun Control (separate A14B weights; not installed TI2V5B): https://docs.comfy.org/tutorials/video/wan/wan2-2-fun-control\n- VRM Animation format: https://vrm.dev/en/vrma/\n- NVIDIA Audio2Face3D (candidate, not installed): https://docs.nvidia.com/nim/digital-human/a2f-3d/latest/index.html\n- Higgsfield Cinema Studio 4.0 web UI: https://higgsfield.ai/blog/cinema-studio-4-0\n- Live Higgsfield MCP catalog read: cinematic_studio_3_0 returned; no generation submitted.\n- Product canon read via GitHub: zeroslove-ai/yuri-room-mvp, codex/yuri-living-core-r1-commercial-pass, YURI_24H_CANON.md.\n- Existing generation evidence: zeroslove-ai/video-production-skills, research/local-video-gen-r0, EXPERIMENT_LOG.md (2026-09-18 recovery and R3 entries).\n\nVendor capability claims are not local quality/performance acceptance. This lab exports ordinary GLB, not VRMA.\n''',encoding='utf-8')
(ROOT/'OPEN_OUTPUTS.cmd').write_text('@echo off\nexplorer "%~dp0local\\output"\n',encoding='utf-8')
(ROOT/'RUN_CPU_PROBE.cmd').write_text('@echo off\npython "%~dp0scripts\\comfy_cpu_probe.py"\npause\n',encoding='utf-8')
(ROOT/'RUN_PROXY_PREVIS.cmd').write_text('@echo off\npython "%~dp0scripts\\init_catalog.py"\nif errorlevel 1 exit /b 1\npython "%~dp0scripts\\run_native.py" --reel\nif errorlevel 1 exit /b 1\npython "%~dp0scripts\\validate_exports.py"\nif errorlevel 1 exit /b 1\nffmpeg -hide_banner -loglevel error -y -framerate 12 -i "%~dp0local\\output\\greeting_frames\\%%04d.png" -c:v libx264 -threads 2 -crf 20 -pix_fmt yuv420p "%~dp0local\\output\\greeting_wave__proxy_previs.mp4"\nif errorlevel 1 exit /b 1\npython "%~dp0scripts\\finalize_receipt.py"\npause\n',encoding='utf-8')
print(json.dumps({'status':'LAB_RECEIPT_WRITTEN','latest_run_directory':str(OUT),'video':str(mp4),'production_ready_clips':0}))
