"""One causal negative: exact source neutral conflicts with frozen current foot contacts."""
import bpy,json,hashlib,sys,math
from pathlib import Path
import numpy as np
from mathutils import Vector
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE))
from r4_appearance_signature import snapshot
from r4_appearance_adapter import ReactionLane
from r4_c1_contact_path_adapter_r1 import ReachFingerLane
from r4_c1_contact_surface_oracle_r3 import SurfaceOracle
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-c1-neutral-frozen-contact-probe-r1';O.mkdir(exist_ok=False);i=json.loads((B/'alpha-c1-neutral-bridge-inspect-r1/C1_NEUTRAL_TARGET_INSPECTION_PRIVATE_R1.json').read_bytes());S=Path(i['source']);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(S)==i['source_SHA'];bpy.ops.wm.open_mainfile(filepath=str(S),use_scripts=False);s=bpy.context.scene;s.frame_set(1);bpy.context.view_layer.update();names=list(bpy.data.actions.keys());before=snapshot(names);rigs=list(i['source_pose_private']);raw={n:{pb.name:(pb.rotation_mode,tuple(pb.location),tuple(pb.rotation_quaternion),tuple(pb.rotation_euler),tuple(pb.rotation_axis_angle),tuple(pb.scale)) for pb in bpy.data.objects[n].pose.bones} for n in rigs};cam=s.camera;cam_original={'loc':cam.location.copy(),'rot':cam.rotation_euler.copy(),'type':cam.data.type,'ortho':cam.data.ortho_scale};original_root=np.array(bpy.data.objects['Assembly_Root'].matrix_world);oracle=SurfaceOracle();source_geometry={n:oracle.geometry(bpy.data.objects[n])[0] for n in ['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4']};lib=Path(i['action_library']);assert sha(lib)==i['action_library_SHA']
with bpy.data.libraries.load(str(lib),link=False) as (src,dst):assert len(src.actions)==8 and not src.objects and not src.meshes and not src.armatures;dst.actions=list(src.actions)
for a in dst.actions:a.use_fake_user=True
lane=ReachFingerLane();lane.on();s.frame_set(61);bpy.context.view_layer.update();endpoint=oracle.geometry(bpy.data.objects['Meshy_Body_NeutralCovered'])[0];endpoint_pairs=oracle.capture();root_end=np.array(bpy.data.objects['Assembly_Root'].matrix_world);assert np.array_equal(root_end,original_root)
floor=i['floor_source_world_z'];foot={};contact_ids={}
for side,ids in i['sole_vertex_ids_private'].items():
 ids=np.array(ids,dtype=int);active=ids[endpoint[ids,2]<=floor+.002];assert len(active)>3;contact_ids[side]=active;delta=source_geometry['Meshy_Body_NeutralCovered'][active]-endpoint[active];horizontal=np.linalg.norm(delta[:,:2],axis=1);foot[side]={'current_grounded_vertices_threshold_world_m':.002,'grounded_vertex_count':len(active),'target_horizontal_move_required_min_m':float(horizontal.min()),'target_horizontal_move_required_median_m':float(np.median(horizontal)),'target_horizontal_move_required_max_m':float(horizontal.max()),'all_current_grounded_vertices_require_horizontal_motion':bool(np.all(horizontal>1e-8)),'centroid_delta_endpoint_minus_source_world_m':i['foot_geometry_target_comparison'][side]['centroid_delta_world_m']}
assert all(v['all_current_grounded_vertices_require_horizontal_motion'] for v in foot.values())
s.render.engine='CYCLES';s.cycles.device='CPU';s.cycles.samples=2;s.cycles.seed=0;s.cycles.use_animated_seed=False;s.cycles.use_denoising=False;s.render.threads_mode='FIXED';s.render.threads=2;s.render.resolution_x=512;s.render.resolution_y=512;s.render.resolution_percentage=100;s.render.image_settings.file_format='JPEG';s.render.image_settings.color_mode='RGB';s.render.image_settings.color_depth='8';s.render.image_settings.quality=92;camera_meta={}
views={'fullbody_front':((.002,-.028,.53),(0,-1,0),1.18),'fullbody_side':((.002,-.028,.53),(1,0,0),1.18),'feet_front':((.002,-.035,.10),(0,-1,0),.5),'feet_top':((.002,-.035,.04),(0,0,1),.5)}
def render_state(label):
 for name,(tar,dir,scale) in views.items():
  target=Vector(tar);cam.data.type='ORTHO';cam.data.ortho_scale=scale;cam.location=target+Vector(dir)*.8;cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(O/f'{label}_{name}.jpg');bpy.ops.render.render(write_still=True);camera_meta[name]={'target':list(target),'location':list(cam.location),'rotation_euler':list(cam.rotation_euler),'ortho_scale':scale,'resolution':[512,512],'same_camera_both_static_states':True}
render_state('C1_ENDPOINT')
# Diagnostic pose probe only: empty temporary Actions bind known source properties, no transition/keys/save.
temps=[];temp_lanes=[]
for name in ['Meshy_Fitted_Rig','Armature','Hair_Rig_R4']:
 a=bpy.data.actions.new('OWNED_NEUTRAL_POSE_PROBE_ONLY_'+name);a.slots.new(id_type='OBJECT',name=name);temps.append(a);tmp=ReactionLane(name);tmp.on(a.name);temp_lanes.append(tmp)
s.frame_set(61)
for name,values in raw.items():
 for bn,pose in values.items():
  pb=bpy.data.objects[name].pose.bones[bn];pb.rotation_mode,pb.location,pb.rotation_quaternion,pb.rotation_euler,pb.rotation_axis_angle,pb.scale=pose
bpy.context.view_layer.update();target_geometry={n:oracle.geometry(bpy.data.objects[n])[0] for n in source_geometry};geometry_error={n:float(np.max(np.abs(target_geometry[n]-a))) for n,a in source_geometry.items()};assert all(v==0 for v in geometry_error.values());assert np.array_equal(original_root,np.array(bpy.data.objects['Assembly_Root'].matrix_world));target_pairs=oracle.capture();render_state('SOURCE_NEUTRAL_TARGET')
# Exact authoritative source-camera target pose, not a motion endpoint or frozen-contact success.
cam.location=cam_original['loc'];cam.rotation_euler=cam_original['rot'];cam.data.type=cam_original['type'];cam.data.ortho_scale=cam_original['ortho'];s.cycles.samples=8;s.render.resolution_x=960;s.render.resolution_y=920;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.filepath=str(O/'EXACT_SOURCE_NEUTRAL_POSE_PROBE.png');bpy.ops.render.render(write_still=True)
for tmp in reversed(temp_lanes):tmp.off()
lane.off()
for a in temps:bpy.data.actions.remove(a)
assert sha(S)==i['source_SHA'];d={'task':'ROOT_PM_C1_SOURCE_REVIEW_TO_NEUTRAL_BRIDGE_R1','source_SHA':i['source_SHA'],'declared_target':i['target_declaration'],'existing_contact_candidate_SHA':i['contact_candidate_SHA'],'hypothesis':'Can both existing C1 endpoint foot contact patches remain frozen in world XY while restoring exact immutable source neutral?','decision':'CAUSAL_NEGATIVE_FROZEN_CONTACT_TARGET_INCOMPATIBLE','target_missing':False,'target_exact_evaluated_body_head_hair_world_error_m':geometry_error,'source_OFF_frame1_vs91_independent':i['source_frame1_vs91_OFF_evaluated_world_max_difference_m'],'root_same_endpoint_and_target_exact':True,'actual_grounded_vertex_constraints':foot,'contact_vertex_ids_private':{n:x.tolist() for n,x in contact_ids.items()},'endpoint_scoped_contact_triangle_counts':{n:len(v) for n,v in endpoint_pairs.items()},'target_scoped_contact_triangle_counts':{n:len(v) for n,v in target_pairs.items()},'proof':'Exact source-neutral geometry fixes each vertex to target T_i. Frozen current contacts require XY=E_i. Every measured grounded contact vertex on BOTH feet has T_i.xy != E_i.xy, so these simultaneous constraints cannot both hold. Timing or pose-lerp smoothing cannot remove this endpoint contradiction.','static_camera_metadata':camera_meta,'no_transition_motion_authored':True,'no_new_saved_Action_candidate':True,'source_and_all_previous_candidates_untouched':True,'temporary_pose_actions_removed':True,'motion_1x_evidence_reused':'Existing contact-cleared C1 four61-frame30fps movies, independently reviewed through-end by Root and Desktop; no new neutral-bridge movie exists or is claimed.','next_smallest_motion_hypothesis':'One staged supported foot replant/weight-transfer source transition. Move one foot at a time with explicit lift and contact timing; preserve other support contact via actual evaluated mesh, then replant the other, and reach exact declared source-neutral body/head/hair pose. Existing C1 frames1..61 and R2 finger Action stay unchanged. Reuse current pose/contact code and avoid previous naive C3 whole-pose foot-sliding recovery.','neutral_return':'HOLD until supported replant candidate passes','TierP':0,'new_export_donor_rig_or_product_changes':False};(O/'FROZEN_CONTACT_CAUSAL_NEGATIVE_PRIVATE_R1.json').write_text(json.dumps(d,indent=2),encoding='utf-8');print('FROZEN_CONTACT_CAUSAL_NEGATIVE',foot,geometry_error,flush=True)
