"""Fresh immutable source + ONLY five Actions/fixed adapter, endpoint and OFF custody."""
import bpy,sys,json,hashlib
from pathlib import Path
import numpy as np
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
from r4_c1_neutral_contact_patch_adapter_r2 import ReachFingerLane
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-c1-neutral-contact-library-qa-r2';O.mkdir(exist_ok=False);i=json.loads((B/'alpha-c1-neutral-bridge-inspect-r1/C1_NEUTRAL_TARGET_INSPECTION_PRIVATE_R1.json').read_bytes());d=json.loads((B/'alpha-c1-neutral-replant-preview-r2/ACTION_ONLY_CUSTODY_R2.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(i['source'])==i['source_SHA'] and sha(d['file'])==d['SHA'];bpy.ops.wm.open_mainfile(filepath=i['source'],use_scripts=False);s=bpy.context.scene;names=list(bpy.data.actions.keys());before=snapshot(names)
def points(name):
 o=bpy.data.objects[name];e=o.evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh();v=np.empty(len(m.vertices)*3,np.float32);m.vertices.foreach_get('co',v);w=np.array(e.matrix_world);v=v.reshape(-1,3).astype(np.float64)@w[:3,:3].T+w[:3,3];e.to_mesh_clear();return v
source={n:points(n) for n in ['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4']}
with bpy.data.libraries.load(d['file'],link=False) as (src,dst):assert len(src.actions)==5 and not src.objects and not src.meshes and not src.armatures;dst.actions=list(src.actions)
for a in dst.actions:a.use_fake_user=True
assert snapshot(names)==before;lane=ReachFingerLane();lane.on();s.frame_set(132);bpy.context.view_layer.update();prev=points('Meshy_Body_NeutralCovered');s.frame_set(133);bpy.context.view_layer.update();errors={n:float(np.max(np.abs(points(n)-v))) for n,v in source.items()};last=float(np.linalg.norm(points('Meshy_Body_NeutralCovered')-prev,axis=1).max());assert all(v==0 for v in errors.values());lane.off();assert snapshot(names)==before;lane.on();s.frame_set(133);bpy.context.view_layer.update()
s.render.engine='CYCLES';s.cycles.device='CPU';s.cycles.samples=8;s.cycles.seed=0;s.cycles.use_animated_seed=False;s.cycles.use_denoising=False;s.render.threads_mode='FIXED';s.render.threads=2;s.render.resolution_x=960;s.render.resolution_y=920;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.image_settings.color_depth='8';s.render.filepath=str(O/'ANIMATION_ON_ENDPOINT_SOURCE_CAMERA_R2.png');bpy.ops.render.render(write_still=True);lane.off();assert sha(i['source'])==i['source_SHA'] and sha(d['file'])==d['SHA'];(O/'SOURCE_PLUS_FIVE_ACTIONS_ORACLE_R2.json').write_text(json.dumps({'source_SHA':i['source_SHA'],'library_SHA':d['SHA'],'named_actions':d['named_actions'],'fixed_adapter':'r4_c1_neutral_contact_patch_adapter_r2.py','fresh_source_only_objects':97,'new_library_objects_meshes_armatures':0,'original78Actions_and_source_snapshot_before_append_after_OFF_exact':True,'ON_endpoint_geometry_component_error_m':errors,'actual_last_adjacent_body_max_vertex_step_m':last,'source_file_SHA_unchanged':True,'ON_endpoint_source_camera_pixels':'PENDING external full RGBA compare','scope':'Exact endpoint/OFF/library-custody PASS, full R2 motion constraints remain FAIL/HOLD, no production promotion','TierP':0},indent=2),encoding='utf-8');print('R2_FIVE_ACTION_LIBRARY_ENDPOINT_OFF_PASS',errors,last,flush=True)
