"""Close one C1 left upper-arm source path packet, preserving causal failures and prior controls."""
from pathlib import Path
import json,hashlib,zipfile
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');L=Path(__file__).resolve().parents[1];D=B/'alpha-c1-contact-path-delivery-r1';E=L/'evidence/alpha-c1-baseline-contact-path-r1';load=lambda p:json.loads(Path(p).read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):
 with p.open('x',encoding='utf-8') as f:json.dump(v,f,indent=2)
c=load(B/'alpha-c1-contact-path-candidate-r1b/C1_CONTACT_PATH_CANDIDATE_PRIVATE_R1.json');off=load(B/'alpha-c1-contact-path-off-qa-r1b/OFF_REOPEN_ORACLE_R3.json');pix=load(B/'alpha-c1-contact-path-off-qa-r1b/PIXEL_ORACLE_R1.json');step=load(B/'alpha-c1-contact-path-candidate-r1b/C1_CONTACT_PATH_STEP_QA_R1.json');skin=load(B/'alpha-c1-contact-path-off-qa-r1b/WHOLE_BODY_STEP_ORACLE_R1.json');actual=load(B/'alpha-c1-contact-path-actual-qa-r1/C1_CONTACT_PAIRED_SURFACE_PRIVATE_R1.json');fixed=load(B/'alpha-c1-contact-path-paired-qa-r1b/C1_CONTACT_PAIRED_SURFACE_PRIVATE_R1.json');ui=load(D/'WHOLE_1X_UI_QA_R1.json');assert pix['PASS'] and c['nonleft_arm_C1_same_time_world_error']==0 and c['sole_vertex_same_C1_max_error_m']==0 and c['composition_start_end_body_world_error_m']==0;assert all(v['ended'] and v['playbackRate']==1 and v['error'] is None for v in ui['end']);assert sha(c['source'])==c['source_SHA'] and sha(c['candidate'])==c['candidate_SHA'];E.mkdir(exist_ok=False)
summary={k:v for k,v in c.items() if k!='frames_private'};summary.update({'same_camera_peak_pixels':load(B/'alpha-c1-contact-path-candidate-r1b/SAME_CAMERA_PEAK_PIXEL_ORACLE_R1.json'),'OFF_reopen':off,'OFF_pixels':pix,'wrist_step_oracle':step,'whole_body_step_oracle':{k:v for k,v in skin.items() if k!='frames_private'},'dynamic_actual_surface_oracle':{k:v for k,v in actual.items() if k!='frames_private'},'fixed_OFF_triangulation_control_oracle':{k:v for k,v in fixed.items() if k!='frames_private'},'normal_speed_UI':ui,'status':'SOURCE_ONLY_LEFT_ARM_CONTACT_'+actual['bounded_contact_subset']+'_NEUTRAL_HOLD','original_neutral':'HOLD: current C1 endpoint differs from immutable source, outside sole LEFT arm ownership; OFF restores true original authority','TierP':0,'prior_checkpoint':'6ce0221','one_hypothesis_only':True,'new_product_export':False,'no_product_or_laptop_edits':True,'scope_limit':'Dominant-weight left arm/hand/digit cohorts, weak webbing/adjacency/full character penetration depth and physical/prop contact are not certified. No Unity AlwaysAnimate/F2/StageB promotion.'});write(E/'C1_CONTACT_SOURCE_MANIFEST_R1.json',summary);write(E/'ACTION_ONLY_CUSTODY_R1.json',load(B/'alpha-c1-contact-path-off-qa-r1b/ACTION_ONLY_CUSTODY_R1.json'))
guards=[]
for run in ['o1-c1-contact-path-candidate-r1','o1-c1-contact-path-candidate-r1b','o1-c1-contact-path-paired-r1','o1-c1-contact-path-paired-r1b','o1-c1-contact-path-actual-r1','o1-c1-contact-path-off-r1b','o1-c1-contact-path-full-r1']:
 p=B/run/'NATIVE_GUARD_RESULT.json';v=load(p);expected='FAIL' if run in ['o1-c1-contact-path-candidate-r1','o1-c1-contact-path-paired-r1'] else 'PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN';assert v['guard_status']==expected;guards.append({'run':run,'SHA':sha(p),'status':v['guard_status'],'wall_seconds':v['wall_seconds']})
write(E/'NATIVE_CUSTODY_R1.json',guards);write(E/'FAILURE_CORRECTION_LOG_R1.json',{'candidate_R1_failure':'Before-side forgot existing C1 face/hair transport; matching assertion correctly failed before candidate save; exit95/drain0. R1b uses original C1 full BaseLane; same8deg motion hypothesis unchanged.','paired_R1_failure':'Incorrect assumption that Blender quad triangulation order/diagonals stay fixed through deformation; topology assertion failed. Original polygons/mesh were unchanged. Preserve failed collector.','paired_R1b_control':'Original OFF triangulation frozen against evaluated world vertices; identical triangle IDs and original polygon topology; all scoped after intersections0.','actual_dynamic_oracle':'Actual per-frame Blender triangulation, identity as vertex-triplets and preserved polygons, all same-frame scoped after intersections0; decisive contact result.','unexecuted_preparation':['o1-c1-contact-path-off-r1'],'previous_candidates_and_closed_packets':'No overwrite/delete/repack; original R4/08caad7/C1/R1/R2 retained.','review_caption_correction':'Copied R1 page incorrectly said endpoint returns to old C1 baseline. R1B explicitly states derivative start pose, changed left-arm endpoint, original-neutral HOLD; original R1 HTML retained, first actual playback used corrected R1B.', 'healthy_processes':'Protected original Blender GUI and product process untouched; only owned native workers launched and drained.'})
(E/'YURI_R4_C1_BASELINE_CONTACT_PATH_R1.md').write_text('''# C1 LEFT baseline contact path: one minimal source candidate

One C1 Action copy, only upper_arm.L four quaternion channels changed. World-outward8deg endpoint shoulder arc moves original wrist outward32.16mm/up10.47mm at start/end; envelope1 at1–7, quintic7–18 to0, exact original peak18–43, quintic43–50 to1, hold50–61. Native wrist/forearm local curves unchanged. All original source78Actions and reused C1/R1/R2 curves preserved. No rig/rest/weight/mesh/material/driver/source change. Reused R2 finger timing exactly; no new donor, export framework, Unity writer or product change.

All61 actual evaluated bodies finite. All non-left-arm bone world matrices/feet/root/facehair transport and source sole vertices match C1 at same clock exactly. Original peak wrist18–43 delta0. Actual wrist step and whole evaluated body step receipts are measured without invented acceptance thresholds. Complete four-view1x through-end and every-frame supplements required. Matched same-camera before/after stills at1,7,18,31,50,61; body/root judged with fixed cameras, hand-close follows derivative wrist only. Existing native shader/material/render noise retained; no appearance recreation or promotion.

Contact oracle checks dominant existing-weight digit/hand/forearm/upper-arm triangle cohorts against body outside corresponding left-hand/arm weighted region and actual head/hair evaluated meshes. Actual per-frame Blender triangulation and same-frame vertex-triplet triangle identities are decisive. Original OFF fixed-triangulation control also recorded. Weak webbing/adjacency/full-body penetration depth/volume or physical grasp are not certified. Numerical/scoped PASS never implies prop/physics/Unity/AlwaysAnimate/MUG/StageB/F2/TierP approval.

C1 endpoint still differs from immutable original R4 neutral (world maximum body component169.29mm); all other C1 body/right-arm/head/pose ownership frozen, so no false original-neutral return claim. Original neutral is restored by OFF only. All source geometry/material slots/nodes/ShapeKeys/skin/rest/drivers/Actions preserved, saved OFF reopened and exact source-camera RGBA compared. SaveAs raw relative locator strings may remap; packed texture bytes/colorspace/resolved properties identical. Action-only library contains8 named playback/control Actions and no object/mesh/rig; fixed adapter appends only Actions and creates/removes one transient R2 finger NLA strip.

Two validation construction failures preserved: R1 before-side omitted C1 rigid face/hair transport, so assertion stopped before save; corrected R1b fixes comparison side only. First surface oracle incorrectly assumed deformation cannot alter Blender quad triangulation; failed assertion retained. Frozen-OFF triangulation control plus actual dynamic triangle oracle resolve this without source edits or changing motion hypothesis. Strict installed guard/owned process/limits unchanged, original healthy GUI/product workers untouched, CPU only under PRODUCT_EXCLUSIVE lease.

Current task ROOT_PM_C1_BASELINE_CONTACT_PATH_R1. Direct Stage A/B source asset supply only, no Player implementation/progress claim. AI dance24-pair reference registration remains preserved; detailed24-row image-only comparison and selected actual-rig QA remain next-boundary work, not contact prerequisites.
''',encoding='utf-8')
files={}
def add(p,n):
 p=Path(p);assert p.is_file() and n not in files;files[n]=p
add(B/'alpha-reach-left-finger-timing-candidate-r2/REACH_LEFT_FINGER_TIMING_CANDIDATE_PRIVATE_R2.json','lineage-metadata/REACH_LEFT_FINGER_TIMING_CANDIDATE_PRIVATE_R2.json')
for n in ['r4_two_input_owned_barrier_broker_r1.py','r4_two_input_live_barrier_wrapper_r1.py']:add(B/'o1-morph67-native-broker-preparation-r4/workflow'/n,'native-workflow/'+n)
add(c['source'],'source/'+Path(c['source']).name);add(c['candidate'],'candidate/'+Path(c['candidate']).name);add(c['lineage_action_library']['file'],'lineage-action-only/'+Path(c['lineage_action_library']['file']).name)
for folder in ['alpha-c1-contact-path-candidate-r1','alpha-c1-contact-path-candidate-r1b','alpha-c1-contact-path-off-qa-r1b','alpha-c1-contact-path-paired-qa-r1b','alpha-c1-contact-path-actual-qa-r1']:
 for p in (B/folder).rglob('*'):
  if p.is_file() and p.suffix not in ['.blend','.blend1']:add(p,'private-evidence/'+folder+'/'+p.relative_to(B/folder).as_posix())
for p in (B/'alpha-c1-contact-path-off-qa-r1b').glob('*.blend'):add(p,'animation-only/'+p.name)
for p in E.iterdir():add(p,'metadata/'+p.name)
for p in D.iterdir():
 if p.is_file():add(p,'review/'+p.name)
add(B/'alpha-c1-contact-path-preview-r1/RENDER_RECEIPT_R1.json','camera/RENDER_RECEIPT_R1.json')
for g in guards:
 for p in (B/g['run']).rglob('*'):
  if p.is_file():add(p,'native-custody/'+g['run']+'/'+p.relative_to(B/g['run']).as_posix())
for p in (L/'scripts').glob('r4_c1_contact*.py'):add(p,'workflow/'+p.name)
for n in ['r4_appearance_adapter.py','r4_appearance_signature.py','native_preservation.py','r4_reach_left_finger_timing_adapter_r2.py']:add(L/'scripts'/n,'workflow/'+n)
add(Path('C:/Users/JAEWAN/.codex/worktrees/common-motion-curation-r1/yuri-room-mvp/common-motion-r1/licenses/Quaternius-LICENSE.txt'),'licenses/Quaternius-LICENSE.txt')
idx={n:{'bytes':p.stat().st_size,'sha256':sha(p)} for n,p in sorted(files.items())};ip=D/'MEMBER_SHA256_INDEX_R1.json';write(ip,idx);add(ip,ip.name);zp=B/'YURI_R4_C1_LEFT_ARM_CONTACT_SOURCE_ONLY_R1_20261004.zip'
with zipfile.ZipFile(zp,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for n,p in sorted(files.items()):z.write(p,n)
with zipfile.ZipFile(zp) as z:
 assert z.testzip() is None
 for n,v in idx.items():
  raw=z.read(n);assert len(raw)==v['bytes'] and hashlib.sha256(raw).hexdigest()==v['sha256']
 receipt={'file':str(zp),'bytes':zp.stat().st_size,'sha256':sha(zp),'members':len(z.namelist()),'indexed_members':len(idx),'CRC_SHA_size_all_members':'PASS','source_SHA':c['source_SHA'],'candidate_SHA':c['candidate_SHA'],'contact_subset':actual['bounded_contact_subset'],'original_neutral_return':'HOLD','TierP':0};write(E/'PRIVATE_PACKET_RECEIPT_R1.json',receipt);write(D/'PRIVATE_PACKET_RECEIPT_R1.json',receipt);print(json.dumps(receipt,indent=2))
