"""Read exact source-frame1 neutral authority versus contact-cleared C1 endpoint."""
import bpy,sys,json,hashlib,math
from pathlib import Path
import numpy as np
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE))
from r4_appearance_signature import snapshot
from r4_c1_contact_path_adapter_r1 import ReachFingerLane
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-c1-neutral-bridge-inspect-r1';O.mkdir(exist_ok=False);c=json.loads((B/'alpha-c1-contact-path-candidate-r1b/C1_CONTACT_PATH_CANDIDATE_PRIVATE_R1.json').read_bytes());S=Path(c['source']);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(S)==c['source_SHA'];bpy.ops.wm.open_mainfile(filepath=str(S),use_scripts=False);s=bpy.context.scene;s.frame_set(1);bpy.context.view_layer.update();names=list(bpy.data.actions.keys());authority=snapshot(names);r=bpy.data.objects['Meshy_Fitted_Rig'];body=bpy.data.objects['Meshy_Body_NeutralCovered'];rigs=['Meshy_Fitted_Rig','Armature','Hair_Rig_R4','AVATAR_FaceBoard']
def geometry(obj):
 e=obj.evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh();a=np.empty(len(m.vertices)*3,np.float32);m.vertices.foreach_get('co',a);w=np.array(e.matrix_world);a=a.reshape(-1,3).astype(np.float64)@w[:3,:3].T+w[:3,3];e.to_mesh_clear();assert np.isfinite(a).all();return a
objects=['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4'];source_mesh={n:geometry(bpy.data.objects[n]) for n in objects};source_pose={n:{pb.name:{'basis':[list(row) for row in pb.matrix_basis],'world':[list(row) for row in bpy.data.objects[n].matrix_world@pb.matrix],'rotation_mode':pb.rotation_mode,'location':list(pb.location),'rotation_quaternion':list(pb.matrix_basis.to_quaternion()),'scale':list(pb.scale)} for pb in bpy.data.objects[n].pose.bones} for n in rigs};floor=float(source_mesh[objects[0]][:,2].min());sole={side:np.where((source_mesh[objects[0]][:,2]<floor+.028)&((source_mesh[objects[0]][:,0]>.00195) if side=='L' else (source_mesh[objects[0]][:,0]<.00195)))[0] for side in ['L','R']};assert all(len(v)>10 for v in sole.values());source_sole={side:source_mesh[objects[0]][idx].copy() for side,idx in sole.items()};s.frame_set(91);bpy.context.view_layer.update();time_independent={n:float(np.max(np.abs(geometry(bpy.data.objects[n])-v))) for n,v in source_mesh.items()};s.frame_set(1);bpy.context.view_layer.update();assert snapshot(names)==authority
lib=B/'alpha-c1-contact-path-off-qa-r1b/YURI_R4_C1_LEFT_ARM_CONTACT_ACTIONS_ONLY_R1.blend'
with bpy.data.libraries.load(str(lib),link=False) as (src,dst):assert len(src.actions)==8 and not src.objects and not src.meshes and not src.armatures;dst.actions=list(src.actions)
for a in dst.actions:a.use_fake_user=True
lane=ReachFingerLane();lane.on();s.frame_set(61);bpy.context.view_layer.update();rows={}
from mathutils import Matrix
for name in rigs:
 rows[name]={}
 for pb in bpy.data.objects[name].pose.bones:
  target=Matrix(source_pose[name][pb.name]['basis']);d=pb.matrix_basis;angle=math.degrees(d.to_quaternion().rotation_difference(target.to_quaternion()).angle);loc=(d.translation-target.translation).length;world=np.array(bpy.data.objects[name].matrix_world@pb.matrix);reference=np.array(source_pose[name][pb.name]['world']);err=float(np.max(np.abs(world-reference)));rows[name][pb.name]={'local_rotation_difference_deg':angle,'local_translation_difference_m':loc,'world_matrix_difference_max':err,'endpoint_basis':[list(row) for row in d]}
endmesh={n:geometry(bpy.data.objects[n]) for n in objects};foot={side:{'source_centroid_world':source_sole[side].mean(0).tolist(),'endpoint_centroid_world':endmesh[objects[0]][idx].mean(0).tolist(),'centroid_delta_world_m':(endmesh[objects[0]][idx].mean(0)-source_sole[side].mean(0)).tolist(),'source_lowest_z_world':float(source_sole[side][:,2].min()),'endpoint_lowest_z_world':float(endmesh[objects[0]][idx,2].min()),'endpoint_max_vertex_world_difference_m':float(np.linalg.norm(endmesh[objects[0]][idx]-source_sole[side],axis=1).max())} for side,idx in sole.items()};lane.off();assert snapshot(names)==authority and sha(S)==c['source_SHA'];summary={n:{bn:{k:v for k,v in item.items() if k!='endpoint_basis'} for bn,item in group.items() if item['local_rotation_difference_deg']>1e-4 or item['local_translation_difference_m']>1e-6 or item['world_matrix_difference_max']>1e-6} for n,group in rows.items()};report={'task':'ROOT_PM_C1_SOURCE_REVIEW_TO_NEUTRAL_BRIDGE_R1','source':str(S),'source_SHA':sha(S),'target_declaration':'Immutable Character_Master_NeckSkin_R4.blend original animation-OFF frame1 pose, source camera authoritative neutral baseline; no guessed idle or donor pose','source_authority_witness':str(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png'),'source_authority_witness_SHA':sha(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png'),'contact_candidate_SHA':c['candidate_SHA'],'action_library':str(lib),'action_library_SHA':sha(lib),'source_fps':24,'candidate_fps':30,'source_frame1_vs91_OFF_evaluated_world_max_difference_m':time_independent,'endpoint_vs_source_world_geometry_max_difference_m':{n:float(np.max(np.abs(endmesh[n]-v))) for n,v in source_mesh.items()},'bone_differences_summary':summary,'source_pose_private':source_pose,'endpoint_pose_private':rows,'sole_vertex_ids_private':{k:v.tolist() for k,v in sole.items()},'foot_geometry_target_comparison':foot,'floor_source_world_z':floor,'OFF_original_signature_restored_exact':True,'no_new_action_or_asset_save':True,'TierP':0};(O/'C1_NEUTRAL_TARGET_INSPECTION_PRIVATE_R1.json').write_text(json.dumps(report,indent=2),encoding='utf-8');print('SOURCE_NEUTRAL_TARGET_DEFINED',time_independent,foot,flush=True)
