"""Preserve one failed thumb correction, source-only artifact and reproducible QA."""
from pathlib import Path
import json,hashlib,zipfile
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');L=Path(__file__).resolve().parents[1];D=B/'alpha-grasp-left-thumb-delivery-c2';E=L/'evidence/alpha-grasp-left-thumb-c2';E.mkdir(exist_ok=False)
def load(p):return json.loads(Path(p).read_bytes())
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):
 with p.open('x',encoding='utf-8') as f:json.dump(v,f,indent=2)
d=load(B/'alpha-grasp-left-thumb-c2/LEFT_THUMB_C2_PRIVATE_MANIFEST.json');r=load(B/'alpha-grasp-left-thumb-preview-c2/THUMB_C2_RENDER_RECEIPT.json');p=load(D/'OFF_PIXEL_ORACLE_C2.json');u=load(D/'WHOLE_1X_UI_QA_C2.json');v=load(D/'VISUAL_QA_C2.json');assert p['PASS'] and r['OFF_full_snapshot_restored'];assert all(x['ended'] and x['playbackRate']==1 and x['error'] is None for x in u['end']);assert sha(d['candidate'])==d['candidate_SHA'] and sha(d['source'])==d['source_SHA'] and sha(d['base_candidate'])==d['base_candidate_SHA']
bad=[x['frame'] for x in d['frames_private'] if x['new_pairs_same_frame']['nonadjacent_all_body']];assert not bad and d['contact_verdict']=='SCOPED_NONADJACENT_SURFACE_PASS';summary={k:x for k,x in d.items() if k not in ['frames_private','native_axis']};summary.update({'native_axis_basis':d['native_axis']['basis'],'opposition_degrees':20,'longitudinal_roll_degrees':10,'source_reference_frame':85,'target_distance_units':'Recorded thumb_tip_to_finger_target_m is RIG-SPACE Blender coordinate distance, not world metric distance. Ratio only; no physicalmm claim.','contact_failure_frames':bad,'baseline_maximum_actual_pairs':{k:max(x['before_counts'][k] for x in d['frames_private']) for k in d['frames_private'][0]['before_counts']},'cameras':r['views'],'OFF_RGBA':p,'normal_speed':u,'visual_QA':v,'action_only':r['library'],'status':'SOURCE_ONLY_SCOPED_NONADJACENT_CONTACT_PASS_HAND_SHAPE_REFERENCE','C2_phase':{'onset_zero_until':61,'ramp_end':85,'release_start':119,'release_end':135,'source_final_wrist_return_onset':136},'preserved_C1_axis_amplitudes':True,'next_bounded_task':'Registered24-pair image-only comparison at safe boundary, absent direct StageA source supply. No C3 thumb amplitude/axis sweep or physical-grasp promotion.','source_appearance_promoted':False,'physics_MUG_F2_Unity_TierP':'HOLD/TierP0','Root_Laptop_Talk':'Independent sole Laptop runtime integration, nonblocking'})
write(E/'LEFT_THUMB_C2_SOURCE_QA_MANIFEST.json',summary)
(E/'YURI_R4_LEFT_THUMB_PHASE_ONLY_C2.md').write_text('# LEFT thumb C2 phase-only source candidate\n\nONE different temporal hypothesis after preserved C1 contact FAIL. Same actual LEFT native axis and20deg opposition/10deg roll; separate COPY of original native Grasp changes only thumb1.L quaternion4channels. Onset after61/ramp62–85, hold85–119, release119–135 before native final wrist return136. Return envelope is based on existing LEFT wrist world track: post120 first step>0.1mm at136, stationary120–135. Earlier secondary wrist reposition103–119 is preserved. Original other290curves/source timing, wrist/body/root/feet/rest/weights/materials/drivers and prior81Actions including original78 remain exact. No C3, new rig/exporter/physics/product/Unity changes.\n\nAll169 inclusive thumb triangles (ANY originalthumb1/2/3 weight>.01) against ALL actual body triangles: baseline0/C2nonadjacent0, palm-inclusive0/other-digit-inclusive0, no failureframes. Weak hand/webbing weights and palm targets are not excluded. Raw shared-vertex adjacency maximum491 and same-triangle0 explicitly reported; new shared-vertex pair identities396 are adjacency/triangulation evidence, not penetration-depth approval. C1 max98/15/94 at47–61 remains FAIL; no repack/overwrite. Scoped surface PASS is not containment/adjacent deformation/physical/MUG grasp certification.\n\nAll169 nonthumb bone matrices and unaffected evaluated geometry difference0, endpoints1/169 base-neutral geometry0. Saved/reopen full OFF snapshot0, authoritative source-camera960×920RGBA changed pixels0. Pure3Actions/0objects/mesh/rig on existing three-rig fixed adapter; source and both prior candidates unchanged.\n\nEntire169frames24fps7.041667sec synced C1-left/C2-right comparisons for LEFT active close and fixed waist: complete decode, actual1x through-end and all-frame paired grids. LEFT wrist world translation follows with constant target offset/fixed rotation; existing fixed waist alone owns wholebody/root/feet visual judgment. C2 avoids early thumb fold into palm during47–61, later moves thumb inward smoothly and returns open before native final return. Fingers remain original loose curl, thumb pads do not form secure grasp; hand-shape REFERENCE ONLY, no convincing MUG/physical grasp/F2/TierP/Unity approval.\n\nTwo unchanged strict native guard jobs/CPU-only/product GPU lease retained. Source/candidate/pure Action/adapter/cameras/contact data/videos/full-member SHA index bundled privately, public Git scripts/scalar QA only. Sole Laptop Talk independent. Next safe-boundary registered24-pair read-only design matrix, only absent direct StageA source supply; image review cannot pass rig/motion/timing/contact.\n',encoding='utf-8')
guards=[]
for run in ['o1-grasp-left-thumb-c2','o1-grasp-left-thumb-preview-c2']:
 f=B/run/'NATIVE_GUARD_RESULT.json';g=load(f);assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN';guards.append({'run':run,'SHA':sha(f),'status':g['guard_status'],'seconds':g['wall_seconds']})
write(E/'NATIVE_CUSTODY_C2.json',guards);files={}
def add(p,n):p=Path(p);assert p.is_file() and n not in files;files[n]=p
add(d['candidate'],'candidate-OFF/'+Path(d['candidate']).name);add(r['library']['file'],'animation-only/'+Path(r['library']['file']).name);add(B/'alpha-grasp-left-thumb-c2/LEFT_THUMB_C2_PRIVATE_MANIFEST.json','private-QA/LEFT_THUMB_C2_PRIVATE_MANIFEST.json');add(B/'alpha-grasp-left-thumb-preview-c2/THUMB_C2_RENDER_RECEIPT.json','private-QA/THUMB_C2_RENDER_RECEIPT.json');add(B/'alpha-grasp-left-thumb-preview-c2/CANDIDATE_OFF_SOURCE_NEUTRAL_C2.png','private-QA/CANDIDATE_OFF_SOURCE_NEUTRAL_C2.png')
for f in D.iterdir():
 if f.is_file():add(f,'review/'+f.name)
for f in E.iterdir():add(f,'metadata/'+f.name)
for g in guards:
 for f in (B/g['run']).rglob('*'):
  if f.is_file():add(f,'native-custody/'+g['run']+'/'+f.relative_to(B/g['run']).as_posix())
for f in (L/'scripts').glob('r4_grasp_left_thumb*.py'):add(f,'workflow/'+f.name)
for n in ['r4_native_grasp_adapter_r1.py','r4_appearance_signature.py','r4_appearance_adapter.py']:add(L/'scripts'/n,'workflow/'+n)
idx={n:{'bytes':f.stat().st_size,'SHA':sha(f)} for n,f in sorted(files.items())};ip=D/'MEMBER_SHA256_INDEX_C2.json';write(ip,idx);add(ip,ip.name);zp=B/'YURI_R4_LEFT_THUMB_PHASE_ONLY_SOURCE_C2_20261005.zip'
with zipfile.ZipFile(zp,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for n,f in sorted(files.items()):z.write(f,n)
with zipfile.ZipFile(zp) as z:
 assert z.testzip() is None
 for n,x in idx.items():raw=z.read(n);assert len(raw)==x['bytes'] and hashlib.sha256(raw).hexdigest()==x['SHA']
 receipt={'file':str(zp),'SHA':sha(zp),'bytes':zp.stat().st_size,'members':len(z.namelist()),'indexed_members':len(idx),'CRC_SHA_size_all':'PASS','source_SHA':d['source_SHA'],'base_candidate_SHA':d['base_candidate_SHA'],'candidate_SHA':d['candidate_SHA'],'library_SHA':r['library']['SHA'],'candidate_verdict':'Scoped nonadjacent contact PASS; hand-shape visual REFERENCE, not secure physical grasp','OFF_pixels':p,'TierP':0};write(E/'PRIVATE_PACKET_RECEIPT_C2.json',receipt);print(json.dumps(receipt,indent=2))
