"""Read ONE existing source Action before independent grounded upper-body reuse."""
import bpy,sys,json,hashlib,math
from pathlib import Path
from mathutils import Euler
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-native-grasp-intake-r1';O.mkdir(exist_ok=False);S=Path('C:/Users/JAEWAN/scratch/YURI_COMMON_MOTION_CURATION_R1/provisional-first4-r1/target-reference/Character_Master_NeckSkin_R4.blend');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();expected='a30fc513a6da3782742c337ee4a50ab3523b82467517d91d84eb0cc0ede2aafa';assert sha(S)==expected;bpy.ops.wm.open_mainfile(filepath=str(S),use_scripts=False);names=list(bpy.data.actions.keys());before=snapshot(names);r=bpy.data.objects['Meshy_Fitted_Rig'];a=bpy.data.actions['MESHY_R2_BODY_GraspHoldRelease'];curves=[fc for la in a.layers for st in la.strips for ba in st.channelbags for fc in ba.fcurves];upper=['spine','chest','neck','head','clavicle.L','clavicle.R','upper_arm.L','upper_arm.R','forearm.L','forearm.R','hand.L','hand.R'];upper += [n+str(j)+'.'+side for side in ['L','R'] for n in ['index','middle','ring','pinky','thumb'] for j in [1,2,3]];upper_curves=[fc for fc in curves if any(fc.data_path.startswith('pose.bones["'+n+'"]') for n in upper)];frames=sorted({float(k.co[0]) for fc in curves for k in fc.keyframe_points});selected=[]
for n in upper:
 paths=[fc for fc in upper_curves if fc.data_path.startswith('pose.bones["'+n+'"]')];euler=[fc for fc in paths if fc.data_path.endswith('.rotation_euler')];q=[fc for fc in paths if fc.data_path.endswith('.rotation_quaternion')];loc=[fc for fc in paths if fc.data_path.endswith('.location')];samples=[]
 for f in [frames[0],frames[len(frames)//2],frames[-1]]:
  v=[next((fc.evaluate(f) for fc in euler if fc.array_index==j),0) for j in range(3)];samples.append({'frame':f,'local_euler':v,'euler_quaternion':list(Euler(v,'XYZ').to_quaternion())})
 selected.append({'bone':n,'source_mode':r.pose.bones[n].rotation_mode,'Euler_curves':len(euler),'quaternion_curves':len(q),'location_curves':len(loc),'sample_private':samples,'maximum_sampled_euler_angle_deg':math.degrees(max(Euler(x['local_euler'],'XYZ').to_quaternion().angle for x in samples))})
assert snapshot(names)==before and sha(S)==expected;(O/'GRASP_SOURCE_ACTION_INTAKE_PRIVATE_R1.json').write_text(json.dumps({'task':'ROOT_PM_NATIVE_TALK_SOURCE_REVIEW_NEXT_EXISTING_WAVE_R1','source':str(S),'source_SHA':expected,'source_action':a.name,'source_action_SHA':before['actions'][a.name],'source_original_actions':len(names),'source_scene_fps':bpy.context.scene.render.fps,'Action_properties':dict(a.items()),'keyframe_range':[min(frames),max(frames)],'keyframe_distinct_times':len(frames),'curves':len(curves),'upper_curves':len(upper_curves),'selected_upper_native_bones':upper,'private_channels':selected,'all_paths':[fc.data_path for fc in curves],'source_no_binding_pose_geometry_rest_skin_material_driver_or_action_change':True,'next':'Reuse this existing Action, reuse already-native upper-body and finger quaternion tracks directly on immutable existing rig; preserve feet/root; intentional original finger motion allowed, original Action untouched; rigid head/hair transport, actual evaluated/OFF/1x QA before any source-only delivery','new_reactions_or_product_changes':False,'TierP':0},indent=2),encoding='utf-8');print('GRASP_SOURCE_INTAKE',a.name,min(frames),max(frames),len(curves),len(upper_curves),[(x['bone'],x['Euler_curves'],x['quaternion_curves']) for x in selected],flush=True)
