"""Reuse existing native GraspHoldRelease upper channels, never rebuild original66 Actions."""
import bpy,sys,json,hashlib,math
from pathlib import Path
import numpy as np
from mathutils import Matrix,Vector
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
from r4_appearance_adapter import ReactionLane
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-native-grasp-candidate-r1b';O.mkdir(exist_ok=False);i=json.loads((B/'alpha-native-grasp-intake-r1/GRASP_SOURCE_ACTION_INTAKE_PRIVATE_R1.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(i['source'])==i['source_SHA'];bpy.ops.wm.open_mainfile(filepath=i['source'],use_scripts=False);s=bpy.context.scene;r=bpy.data.objects['Meshy_Fitted_Rig'];names=list(bpy.data.actions.keys());before=snapshot(names);assert i['keyframe_range']==[1.0,169.0];old=bpy.data.actions[i['source_action']];assert before['actions'][old.name]==i['source_action_SHA'];allowed=set(i['selected_upper_native_bones']);assert all(r.pose.bones[n].rotation_mode=='QUATERNION' for n in allowed)
def points(n='Meshy_Body_NeutralCovered'):
 e=bpy.data.objects[n].evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh();v=np.empty(len(m.vertices)*3,np.float32);m.vertices.foreach_get('co',v);w=np.array(e.matrix_world);v=v.reshape(-1,3).astype(np.float64)@w[:3,:3].T+w[:3,3];e.to_mesh_clear();return v
source={n:points(n) for n in ['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4']};v0=source['Meshy_Body_NeutralCovered'];floor=v0[:,2].min();sole=np.where(v0[:,2]<floor+.028)[0];lowernames=['root','pelvis','thigh.L','thigh.R','shin.L','shin.R','foot.L','foot.R','toe.L','toe.R'];lower={n:np.array(r.matrix_world@r.pose.bones[n].matrix) for n in lowernames};root=np.array(bpy.data.objects['Assembly_Root'].matrix_world);fingerraw={pb.name:np.array(pb.matrix_basis) for pb in r.pose.bones if pb.name.startswith(('index','middle','ring','pinky','thumb'))};refhead=r.matrix_world@r.pose.bones['head'].matrix;refs={n:bpy.data.objects[n].matrix_world@bpy.data.objects[n].pose.bones[bn].matrix for n,bn in [('Armature','Root'),('Hair_Rig_R4','Hair_HeadRoot')]}
a=old.copy();a.name='YURI_R4_NATIVE_GRASP_HAND_EXISTING_ACTION_R1';a.use_fake_user=True;a['source_fps']=24;a['source_action']=old.name;a['source_action_SHA']=i['source_action_SHA'];a['scope']='Existing native Quaternion+location curves of12upper+30finger bones copied EXACT; all other curves removed from COPY only. Original78Actions preserved. Stationary source pelvis/legs/root; original intentional finger curve motion.'
for la in a.layers:
 for st in la.strips:
  for ba in st.channelbags:
   for fc in list(ba.fcurves):
    if not any(fc.data_path.startswith('pose.bones["'+n+'"]') for n in allowed):ba.fcurves.remove(fc)
curves=[fc for la in a.layers for st in la.strips for ba in st.channelbags for fc in ba.fcurves];assert len(curves)==294 and all(not fc.data_path.endswith('rotation_euler') for fc in curves);actions={r.name:a.name};lanes=[]
lane=ReactionLane();lane.on(a.name);lanes.append(lane)
for obj in ['Armature','Hair_Rig_R4']:
 action=bpy.data.actions.new('YURI_R4_NATIVE_GRASP_HAND_'+('HEAD' if obj=='Armature' else 'HAIR')+'_TRANSPORT_R1');action.use_fake_user=True;action.slots.new(id_type='OBJECT',name=obj);action['source_fps']=24;actions[obj]=action.name;ln=ReactionLane(obj);ln.on(action.name);lanes.append(ln)
rows=[];prev=v0.copy();maxsole=0;maxlower=0;maxfinger=0;maxbody=0
for f in range(1,170):
 s.frame_set(f);bpy.context.view_layer.update();delta=(r.matrix_world@r.pose.bones['head'].matrix)@refhead.inverted();delta=Matrix.LocRotScale(delta.translation,delta.to_quaternion(),Vector((1,1,1)))
 for obj,bn in [('Armature','Root'),('Hair_Rig_R4','Hair_HeadRoot')]:
  o=bpy.data.objects[obj];pb=o.pose.bones[bn];basis=pb.bone.matrix_local.inverted()@(o.matrix_world.inverted()@delta@refs[obj]);pb.location=basis.translation;pb.rotation_quaternion=basis.to_quaternion();pb.keyframe_insert('location',frame=f,group=bn);pb.keyframe_insert('rotation_quaternion',frame=f,group=bn)
 bpy.context.view_layer.update();v=points();assert np.isfinite(v).all();soleerror=float(np.max(np.abs(v[sole]-v0[sole])));maxsole=max(maxsole,soleerror);lowerror=max(float(np.max(np.abs(np.array(r.matrix_world@r.pose.bones[n].matrix)-x))) for n,x in lower.items());maxlower=max(maxlower,lowerror);fingererror=max(float(np.max(np.abs(np.array(r.pose.bones[n].matrix_basis)-x))) for n,x in fingerraw.items());maxfinger=max(maxfinger,fingererror);assert np.array_equal(root,np.array(bpy.data.objects['Assembly_Root'].matrix_world));diff=float(np.max(np.abs(v-v0)));maxbody=max(maxbody,diff);step=float(np.linalg.norm(v-prev,axis=1).max());prev=v.copy();rows.append({'frame':f,'body_source_max_component_delta_m':diff,'body_max_vertex_step_m':step,'source_sole_component_error_m':soleerror,'lower_bone_world_matrix_error':lowerror,'intentional_finger_local_matrix_delta':fingererror,'wrist_world':{side:list(r.matrix_world@r.pose.bones['hand.'+side].head) for side in ['L','R']}})
 if f==1:first=v.copy()
 if f%24==1:print('NATIVE_GRASP_FRAME',f,diff,soleerror,lowerror,flush=True)
last=v.copy();assert maxbody>1e-5;assert maxsole==0 and maxlower==0 and maxfinger>1e-5
for ln in reversed(lanes):ln.off()
assert snapshot(names)==before;out=O/'Character_R4_NativeGraspHand_CANDIDATE_OFF_R1B_20261004.blend';bpy.ops.wm.save_as_mainfile(filepath=str(out));assert sha(i['source'])==i['source_SHA'];d={'task':'ROOT_PM_NATIVE_GRASP_SOURCE_REVIEW_NEXT_EXISTING_WAVE_R1','source':i['source'],'source_SHA':i['source_SHA'],'candidate':str(out),'candidate_SHA':sha(out),'candidate_bytes':out.stat().st_size,'original_actions':len(names),'source_action':old.name,'source_action_SHA':i['source_action_SHA'],'source_Action_already_NATIVE_Quaternion':True,'Euler_conversion_rebuild_needed':False,'selected_upper_and_finger_bones':sorted(allowed),'copied_original_upper_and_finger_curves':294,'additive_actions':actions,'frame_range':[1,169],'source_scene_fps':24,'source_Action_Sample_rate':24,'duration_sec':169/24,'source_sole_world_error_m':maxsole,'lower_bone_world_error':maxlower,'intentional_finger_local_matrix_max_motion':maxfinger,'root_exact_all169':True,'all_body_mesh_samples_finite':True,'max_native_body_source_component_motion_m':maxbody,'maximum_body_vertex_step_m':max(x['body_max_vertex_step_m'] for x in rows),'first_vs_original_neutral_body_component_error_m':float(np.max(np.abs(first-v0))),'last_vs_original_neutral_body_component_error_m':float(np.max(np.abs(last-v0))),'first_last_body_component_error_m':float(np.max(np.abs(first-last))),'original78Actions_and_OFF_source_snapshot_exact':True,'frames_private':rows,'semantic':'Hand-oriented native GraspHoldRelease reused from existing66 source, original upper/finger native curves. Face/gaze/drivers preserved neutral, head/hair rigid transport. No physical prop/grasp, final facial acting/NorthStar/TierP/Unity quality claim.','stage':'Independent source motion supply; neutral replant R1/R2 remain closed FAIL/HOLD and nonblocking','visual_normal_speed_contact_OFF_reopen':'PENDING','TierP':0};(O/'NATIVE_GRASP_CANDIDATE_PRIVATE_R1B.json').write_text(json.dumps(d,indent=2),encoding='utf-8');print('NATIVE_GRASP_CANDIDATE',sha(out),maxbody,maxsole,d['first_last_body_component_error_m'],flush=True)
