"""ONE view exact769 native poses; no authoring, source/candidate remain OFF untouched."""
import bpy,sys,json,hashlib,ast
from pathlib import Path
import numpy as np
from mathutils import Vector
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
from r4_native_tour_adapter_r1 import NativeTourLane
def run(view):
 B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-native-tour-recovery-r2';O=B/('alpha-native-tour-capture-'+view+'-r1');O.mkdir(exist_ok=False);m=json.loads((P/'NATIVE_TOUR_RECOVERY_PRIVATE_R2.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(m['candidate'])==m['candidate_SHA'];bpy.ops.wm.open_mainfile(filepath=m['candidate'],use_scripts=False);s=bpy.context.scene;names=list(m['original78_signature_private']['actions']);before=snapshot(names);assert before==m['original78_signature_private']
 module=ast.parse((H/'r4_existing_reach_contact_closure_r1.py').read_text(encoding='utf8'));ns={'bpy':bpy,'np':np,'fixed':{}};exec(compile(ast.Module(body=[x for x in module.body if isinstance(x,ast.FunctionDef) and x.name=='geom'],type_ignores=[]),'<same_actual_mesh>','exec'),ns);geom=ns['geom'];mesh_names=['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4'];cam=s.camera;savecam=(cam.location.copy(),cam.rotation_euler.copy(),cam.data.type,cam.data.ortho_scale);changes=[(s.render,'engine','CYCLES'),(s.cycles,'device','CPU'),(s.cycles,'samples',2),(s.cycles,'seed',0),(s.cycles,'use_animated_seed',False),(s.cycles,'use_denoising',False),(s.render,'threads_mode','FIXED'),(s.render,'threads',2),(s.render,'resolution_x',256),(s.render,'resolution_y',256),(s.render,'resolution_percentage',100),(s.render.image_settings,'file_format','JPEG'),(s.render.image_settings,'color_mode','RGB'),(s.render.image_settings,'color_depth','8'),(s.render.image_settings,'quality',92),(s.render,'filepath','')];saved=[(o,k,getattr(o,k)) for o,k,_ in changes]
 for o,k,v in changes:setattr(o,k,v)
 direction={'front':(0,-1,0),'quarter':(.6,-1,0),'side':(1,0,0)}[view];target=Vector((.002,-.028,.53));cam.data.type='ORTHO';cam.data.ortho_scale=1.18;cam.location=target+Vector(direction).normalized()*.8;cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();camera={'type':'ORTHO','scale':1.18,'target':list(target),'location':list(cam.location),'rotation_euler':list(cam.rotation_euler),'resolution':[256,256],'view':view,'fps':m['fps'],'source_frames':m['frames']};ln=NativeTourLane();ln.on();rows=[]
 for ix,f in enumerate(range(m['frames'][0],m['frames'][1]+1)):
  s.frame_set(f);bpy.context.view_layer.update();expected=m['all_rows_private'][ix]['actual_mesh_hash_private'];actual={n:hashlib.sha256(geom(bpy.data.objects[n])[0].tobytes()).hexdigest() for n in mesh_names};assert actual==expected,('Fresh serialized bound actual mesh differs from source measurement',f,actual,expected);s.render.filepath=str(O/f'{ix+1:04}.jpg');bpy.ops.render.render(write_still=True);rows.append({'source_frame':f,'encoded_ordinal':ix+1,'all_measured_BODY_HEAD_HAIR_actual_geometry_exact':True,'file_SHA':sha(s.render.filepath)})
  if f%96==1:print('TOUR_NATIVE_CAPTURE',view,f,flush=True)
 ln.off();cam.location,cam.rotation_euler,cam.data.type,cam.data.ortho_scale=savecam;s.render.resolution_x=960;s.render.resolution_y=920;s.cycles.samples=8;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.filepath=str(O/'OFF_SOURCE_CAMERA_NEUTRAL.png');bpy.ops.render.render(write_still=True)
 for o,k,v in saved:setattr(o,k,v)
 assert snapshot(names)==before and sha(m['candidate'])==m['candidate_SHA'];(O/'NATIVE_TOUR_CAPTURE_PRIVATE_R1.json').write_text(json.dumps({'same_candidate_SHA':m['candidate_SHA'],'all769_native_frames_complete':True,'camera':camera,'source78_OFF_equal':True,'frames_private':rows},indent=2),encoding='utf8');print('TOUR_FULL_VIEW_COMPLETE',view,len(rows),flush=True)
