"""Reopen, pure three-Action library, every-frame fixed two-view native source QA."""
import bpy,json,sys,hashlib
from pathlib import Path
from mathutils import Vector
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_native_grasp_adapter_r1 import NativeGraspLane,ACTIONS
from r4_appearance_signature import snapshot
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-native-grasp-preview-r1';O.mkdir(exist_ok=False);d=json.loads((B/'alpha-native-grasp-candidate-r1/NATIVE_GRASP_CANDIDATE_PRIVATE_R1.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();P=Path(d['candidate']);assert sha(P)==d['candidate_SHA'];bpy.ops.wm.open_mainfile(filepath=str(P),use_scripts=False);s=bpy.context.scene;cam=s.camera;cloc=cam.location.copy();crot=cam.rotation_euler.copy();scale=cam.data.ortho_scale;names=list(bpy.data.actions.keys());before=snapshot(names);lane=NativeGraspLane();lane.on();s.frame_set(61);bpy.context.view_layer.update();lane.off();assert snapshot(names)==before
lib=O/'YURI_R4_NATIVE_GRASP_HAND_ACTIONS_ONLY_R1.blend';bpy.data.libraries.write(str(lib),{bpy.data.actions[n] for n in ACTIONS.values()},fake_user=True)
with bpy.data.libraries.load(str(lib),link=False) as (src,dst):assert sorted(src.actions)==sorted(ACTIONS.values()) and not src.objects and not src.meshes and not src.armatures
(O/'ACTION_ONLY_CUSTODY_R1.json').write_text(json.dumps({'file':str(lib),'SHA':sha(lib),'bytes':lib.stat().st_size,'Actions':ACTIONS,'named_actions':3,'objects':0,'meshes':0,'armatures':0,'source_fps':24,'frame_range':[1,121],'existing_66_source_Action_reused':'Original MESHY_R2_BODY_GraspHoldRelease upper+finger294native curves copied exactly into separate Action; source original unchanged','Face_gaze':'Original keys/drivers preserved neutral, body head rigid transport only','canonical_character':False,'TierP':0},indent=2),encoding='utf-8')
s.render.engine='CYCLES';s.cycles.device='CPU';s.cycles.samples=2;s.cycles.seed=0;s.cycles.use_animated_seed=False;s.cycles.use_denoising=False;s.render.threads_mode='FIXED';s.render.threads=2;s.render.resolution_x=384;s.render.resolution_y=384;s.render.resolution_percentage=100;s.render.image_settings.file_format='JPEG';s.render.image_settings.color_mode='RGB';s.render.image_settings.color_depth='8';s.render.image_settings.quality=92;meta={};lane.on()
for view,target,direction,size in [('fullbody_front',(.002,-.028,.53),(0,-1,0),1.18),('waist_3q',(.002,-.028,.79),(.6,-1,0),.62)]:
 p=O/view;p.mkdir();tar=Vector(target);cam.data.type='ORTHO';cam.data.ortho_scale=size;cam.location=tar+Vector(direction).normalized()*.8;cam.rotation_euler=(tar-cam.location).to_track_quat('-Z','Y').to_euler();meta[view]={'target':list(tar),'location':list(cam.location),'rotation_euler':list(cam.rotation_euler),'ortho_scale':size,'resolution':[384,384],'fixed':True,'frames':[1,121],'fps':24}
 for f in range(1,122):s.frame_set(f);bpy.context.view_layer.update();s.render.filepath=str(p/f'{f:04}.jpg');bpy.ops.render.render(write_still=True)
 print('NATIVE_GRASP_COMPLETE_VIEW',view,121,flush=True)
lane.off();cam.location=cloc;cam.rotation_euler=crot;cam.data.ortho_scale=scale;s.cycles.samples=8;s.render.resolution_x=960;s.render.resolution_y=920;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.render.filepath=str(O/'CANDIDATE_OFF_SOURCE_NEUTRAL_R1.png');bpy.ops.render.render(write_still=True);assert sha(P)==d['candidate_SHA'];(O/'NATIVE_GRASP_RENDER_RECEIPT_R1.json').write_text(json.dumps({'candidate_SHA':d['candidate_SHA'],'OFF_reopen_on_off_binding_and_source_snapshot_exact':True,'Action_only_lib_SHA':sha(lib),'views':meta,'complete121_frames_two_views':True,'source_materials_shader_geometry_drivers_untouched':True,'normal_speed':'PENDING encoded actual1x playback','source_fps':24,'source_scene_fps_preserved':24,'TierP':0},indent=2),encoding='utf-8')
