"""Private same-hand source packet and public scalar receipts; retain causal controls."""
from pathlib import Path
import json,hashlib,zipfile
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');L=Path(__file__).resolve().parents[1];D=B/'alpha-reach-left-finger-delivery-r1';E=L/'evidence/alpha-reach-left-finger-source-r1';load=lambda p:json.loads(Path(p).read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):
 with p.open('x',encoding='utf8') as f:json.dump(v,f,indent=2)
c=load(B/'alpha-reach-left-finger-candidate-r1/REACH_LEFT_FINGER_CANDIDATE_PRIVATE_R1.json');off=load(B/'alpha-reach-left-finger-off-qa-r1/OFF_REOPEN_ORACLE_R3.json');pixel=load(B/'alpha-reach-left-finger-off-qa-r1/PIXEL_ORACLE_R1.json');surface=load(B/'alpha-reach-left-finger-surface-qa-r1/REACH_FINGER_SURFACE_QA_PRIVATE_R1.json');ui=load(D/'WHOLE_1X_UI_QA_R1.json');right=load(B/'alpha-reach-finger-candidate-r2/REACH_FINGER_CANDIDATE_PRIVATE_R2.json');bad=load(B/'alpha-reach-finger-candidate-r1/REACH_FINGER_CANDIDATE_PRIVATE_R1.json');right_surface=load(B/'alpha-reach-finger-surface-qa-r2/REACH_FINGER_SURFACE_QA_PRIVATE_R1.json');cause=load(D/'LEFT_FINGER_COLLISION_CAUSE_R1.json')
assert pixel['PASS'] and c['nonfinger_C1_same_time_world_matrix_max_error']==0 and c['composition_start_end_body_local_error_m']==0 and all(v['ended'] and v['playbackRate']==1 and v['error'] is None for v in ui['end']);assert sha(c['source'])==c['source_SHA'] and sha(c['candidate'])==c['candidate_SHA'];E.mkdir(exist_ok=False)
summary={k:v for k,v in c.items() if k not in ['frames_private','left_finger_inventory_private','left_finger_axes_private']};summary.update({'left_native_inventory':{n:{k:v for k,v in x.items() if k!='rest_matrix'} for n,x in c['left_finger_inventory_private'].items()},'OFF_reopen':off,'OFF_pixels':pixel,'actual_surface_QA':{k:v for k,v in surface.items() if k!='frames_private'},'normal_speed_UI':ui,'visual_verdict':ui['verdict'],'original_right_Action_preserved_unbound':True,'causal_contact_comparison':cause,'source_status':'SOURCE_ONLY_SAME_HAND_TECH_PASS_CONTACT_FAIL_HOLD','overlap_implementation_reference':'https://github.com/blender/blender/blob/main/source/blender/python/mathutils/mathutils_bvhtree.cc#L504','neutral_return':'HOLD: end equals C1 baseline exactly, not immutable R4 original neutral; source neutral restored by OFF only','prop_contact_physics_Unity_MUG_StageB_F2':'HOLD','TierP':0,'product_or_laptop_changes':False,'new_donor_corpus_count':0});write(E/'SAME_HAND_SOURCE_MANIFEST_R1.json',summary);write(E/'ACTION_ONLY_CUSTODY_R1.json',load(B/'alpha-reach-left-finger-off-qa-r1/ACTION_ONLY_CUSTODY_R1.json'))
failure={'R1_failed_saved_candidate':{'file':bad['candidate'],'SHA':bad['candidate_SHA'],'source_OFF_preserved':True,'error':'Saved OFF derivative lost loaded orphan Actions without explicit fake-user retention; reopened lookup YURI_R4_C1_REACH_BODY_R1 failed; owned exit95 and drain confirmed'},'R2_Action_retention_correction':{'file':right['candidate'],'SHA':right['candidate_SHA'],'all_loaded_actions_fake_user':True,'R1_R2_existing_Action_signatures_and_all61_samples_equal':bad['existing_action_signatures']==right['existing_action_signatures'] and bad['frames_private']==right['frames_private'],'OFF_pixels':load(B/'alpha-reach-finger-off-qa-r2/PIXEL_ORACLE_R2.json'),'UI':load(B/'alpha-reach-finger-delivery-r2/WHOLE_1X_UI_QA_R2.json'),'semantic_defects':right['semantic_defects'],'right_digit_body_other_max_triangle_overlaps':right_surface['max_overlap_counts'],'source_status':'RIGHT_COUNTER_HAND_CAUSAL_FAILURE_CONTACT_AND_LATERALITY_HOLD'},'preparation_failure':'off-r2 was prepared before candidate receipt existed; no native process launched from missing config. Partial preparation preserved; fresh off-r2b after completed candidate passed.','unexecuted_exact_packets':['o1-reach-finger-probe-r1','o1-reach-finger-off-r2','o1-reach-left-finger-candidate-r1'],'same_hand_supplement':'One separate left native Action, actual left local axes verified; original right Action/C1 body curves preserved.','remaining_defect':'Neutral-return and contact still HOLD; no body recovery bridge or solver under this scope','next_alternative':'One finger-timing-only candidate that releases fully before frame51 return collision while preserving all C1 body/wrist curves; inherited C1 contact and original-neutral HOLD remain'};assert failure['R2_Action_retention_correction']['R1_R2_existing_Action_signatures_and_all61_samples_equal'];write(E/'CAUSAL_FAILURE_CORRECTION_R1.json',failure)
guards=[]
for run in ['o1-reach-finger-candidate-r1','o1-reach-finger-off-r1','o1-reach-finger-candidate-r2','o1-reach-finger-off-r2b','o1-reach-finger-probe-r2','o1-reach-finger-full-r2','o1-reach-finger-surface-r2','o1-reach-left-finger-candidate-r1b','o1-reach-left-finger-off-r1','o1-reach-left-finger-probe-r1','o1-reach-left-finger-full-r1','o1-reach-left-finger-surface-r1','o1-reach-left-finger-surface-baseline-r1']:
 p=B/run/'NATIVE_GUARD_RESULT.json';v=load(p);expected='FAIL' if run=='o1-reach-finger-off-r1' else 'PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN';assert v['guard_status']==expected;guards.append({'run':run,'SHA':sha(p),'status':expected,'wall_seconds':v['wall_seconds']})
write(E/'NATIVE_CUSTODY_R1.json',guards)
text='''# C1 LEFT reach + separate LEFT finger layer: reversible source candidate

61frames30fps (2.033333sec movie). C1 body/arm/wrist/Assembly_Root and original rigid head/hair transport curves are reused unchanged at the same source time. New left finger Action owns only15 existing left digit quaternion paths; no overlapping C1 paths, fixed NLA scale1/REPLACE, no retimed body. Right finger Action remains unchanged and unbound. Actual original left rest matrices/local axes/weights/parents were inspected; native palm-plane axes, not copied Euler signs, create minimal12/18/10deg digit and4/6/4deg thumb curl with1–4frame stagger. Open1–11, curl12–31, hold32–38, release39–57, C1 baseline return58–61. No full-fist/opposition/physical grasp claim.

All61 actual evaluated body meshes finite; all non-left-finger body-bone world matrices, root carrier and existing head/hair transport match C1 at identical times exactly. End evaluated body equals start C1 baseline exactly. End differs from original immutable R4 neutral; original-neutral return HOLD, OFF restoration recovers original authority. Original78Actions, rig/rest/weights/geometry/materials/textures/ShapeKeys/face/gaze drivers unchanged. Original source a30fc513 unchanged; OFF before/after signature exact, reopen all6 appended Actions retained with identical curve signatures, source camera decoded RGBA diff0. Relative texture locator strings remap at SaveAs; packed bytes/colorspace/resolved properties identical. No saved NLA tracks; explicit fixed adapter creates transient C1+left strips and removes/restores them on off(). Source scene24fps retained; consume Action source_fps30.

Source-only front/side/fullbody fixed cameras preserve world evidence. Hand-close camera follows existing C1 wrist/direction only (not finger tips or arbitrary pose stabilization), and every camera frame is recorded; root/body/trajectory are judged in fixed views. Four full61-frame renders, complete decode and actual1x UI through-end. Evaluated dominant-weight digit triangle cohorts and non-hand body surface BVH checks supplement actual visual review; weak-weight webbing/palm, same-digit folds and exact whole-character collision remain outside the certificate. Manifest contains actual results and limits. Prop/socket/contact/IK/physics/MUG/Unity/AlwaysAnimate/TierP/StageB/F2/F3 HOLD.

Controls preserved: R1 saved Action-custody failure retained, R2 correct retention with C1 same-time matrix equality and original OFF pixels0, four1x movies. R2 used right curl against LEFT reach and had actual right-digit/body intersections; never accepted as grasp. Same-hand correction adds one left Action without changing right/C1/source. No third motion approach, source rig reconstruction, new donor or export architecture. One premature off preparation failed before launch; fresh packet after completed dependency passed. No guard changes. CPU-only within current shared GPU lease; protected original GUI Blender and Laptop/product repositories untouched.

Private packet separates original source, saved animation-OFF derivative, six-Action library (existing C1four + preserved right + new left), fixed playback adapter, clock/ownership/camera metadata, failure/control evidence and source movies. Append Actions only; bind ReachFingerLane from r4_reach_left_finger_adapter_r1.py, on(), evaluate1..61 at30fps, then off(). Source is canonical; candidates/GameRig are experiments only. Exact scoped guards/path remapping are required for relocated native reproduction. No main merge.

Actual C1-only left digit/body triangle intersections already exist; same-clock new curl adds pinky/body max29 pairs and ring/body count increments at return frames51–55. Inter-digit pairs remain0; counts are surface-pair intersections, not penetration depth. Source collision quality FAIL/HOLD. One finger-timing-only alternative is to finish release before frame51, preserving all original C1 body/wrist curves; inherited C1 contacts and original-neutral return still HOLD. This source checkpoint does not authorize a product writer or physical grasp claim.
''';(E/'YURI_R4_C1_SAME_HAND_SOURCE_R1.md').write_text(text,encoding='utf8')
files={}
def add(p,n):
 p=Path(p);assert p.is_file() and n not in files;files[n]=p
add(c['source'],'source/'+Path(c['source']).name);add(c['candidate'],'candidate/'+Path(c['candidate']).name);add(right['candidate'],'causal-controls/'+Path(right['candidate']).name)
for folder in ['alpha-reach-left-finger-candidate-r1','alpha-reach-left-finger-off-qa-r1','alpha-reach-left-finger-surface-qa-r1','alpha-reach-left-finger-surface-baseline-r1','alpha-reach-finger-candidate-r1','alpha-reach-finger-candidate-r2','alpha-reach-finger-off-qa-r2','alpha-reach-finger-surface-qa-r2']:
 for p in (B/folder).rglob('*'):
  if p.is_file() and p.suffix not in ['.blend','.blend1']:add(p,'private-evidence/'+folder+'/'+p.relative_to(B/folder).as_posix())
for p in (B/'alpha-reach-left-finger-off-qa-r1').glob('*.blend'):add(p,'animation-only/'+p.name)
for entry in c['lineage_inputs']:add(entry['file'],'lineage-action-only/'+Path(entry['file']).name)
for p in E.iterdir():add(p,'metadata/'+p.name)
for folder in [D,B/'alpha-reach-finger-delivery-r2']:
 for p in folder.iterdir():
  if p.is_file():add(p,'review/'+folder.name+'/'+p.name)
for g in guards:
 for p in (B/g['run']).rglob('*'):
  if p.is_file():add(p,'native-custody/'+g['run']+'/'+p.relative_to(B/g['run']).as_posix())
for folder in ['alpha-reach-left-finger-preview-r1','alpha-reach-finger-preview-r2']:add(B/folder/'RENDER_RECEIPT_R1.json','camera/'+folder+'_RENDER_RECEIPT_R1.json')
for p in (L/'scripts').glob('r4_reach*finger*.py'):add(p,'workflow/'+p.name)
for n in ['r4_appearance_adapter.py','r4_appearance_signature.py','native_preservation.py']:add(L/'scripts'/n,'workflow/'+n)
add(Path('C:/Users/JAEWAN/.codex/worktrees/common-motion-curation-r1/yuri-room-mvp/common-motion-r1/licenses/Quaternius-LICENSE.txt'),'licenses/Quaternius-LICENSE.txt')
idx={n:{'bytes':p.stat().st_size,'sha256':sha(p)} for n,p in sorted(files.items())};ip=D/'MEMBER_SHA256_INDEX_R1.json';write(ip,idx);add(ip,ip.name);zp=B/'YURI_R4_C1_REACH_SAME_HAND_SOURCE_ONLY_R1_20261004.zip'
with zipfile.ZipFile(zp,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for n,p in sorted(files.items()):z.write(p,n)
with zipfile.ZipFile(zp) as z:
 assert z.testzip() is None
 for n,v in idx.items():
  raw=z.read(n);assert len(raw)==v['bytes'] and hashlib.sha256(raw).hexdigest()==v['sha256']
 receipt={'file':str(zp),'bytes':zp.stat().st_size,'sha256':sha(zp),'members':len(z.namelist()),'indexed_members':len(idx),'CRC_SHA_size_all_members':'PASS','source_SHA':c['source_SHA'],'candidate_SHA':c['candidate_SHA'],'Action_library_SHA':load(B/'alpha-reach-left-finger-off-qa-r1/ACTION_ONLY_CUSTODY_R1.json')['sha256'],'source_status':'SOURCE_ONLY_SAME_HAND_TECH_PASS_CONTACT_FAIL_HOLD','TierP':0};write(E/'PRIVATE_PACKET_RECEIPT_R1.json',receipt);write(D/'PRIVATE_PACKET_RECEIPT_R1.json',receipt);print(json.dumps(receipt,indent=2))
