"""Existing Wave missing RIGHT finger/webbing QA only: unchanged action, inclusive surface and full close view."""
import bpy,sys,json,hashlib,ast,gzip
from pathlib import Path
import numpy as np
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view
from mathutils.bvhtree import BVHTree
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
from r4_appearance_adapter import ReactionLane
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-social-wave-hand-quality-r2';O.mkdir(exist_ok=False);L=H.parent;m=json.loads((L/'evidence/alpha-social-greeting-source-candidate-r1/SOCIAL_GREETING_MANIFEST_R1.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(m['source'])==m['source_SHA'] and sha(m['candidate'])==m['candidate_SHA'];bpy.ops.wm.open_mainfile(filepath=m['candidate'],use_scripts=False);s=bpy.context.scene;r=bpy.data.objects['Meshy_Fitted_Rig'];body=bpy.data.objects['Meshy_Body_NeutralCovered'];names=list(bpy.data.actions.keys());before=snapshot(names)
for fn,defs in [('r4_native_walk_source_supply_r1.py',['contact']),('r4_existing_reach_contact_closure_r1.py',['geom'])]:
 tree=ast.parse((H/fn).read_text(encoding='utf8'));exec(compile(ast.Module(body=[x for x in tree.body if isinstance(x,ast.FunctionDef) and x.name in defs],type_ignores=[]),'<same_inclusive_actual_surface>','exec'))
previous=json.loads((B/'alpha-social-wave-hand-quality-r1/WAVE_HAND_QUALITY_PRIVATE_R1.json').read_bytes());fixed={};mesh_names=['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4'];neutral={n:geom(bpy.data.objects[n]) for n in mesh_names};gn={g.index:g.name for g in body.vertex_groups};handids=np.array([v.index for v in body.data.vertices if any(gn[g.group] in ['hand.R','forearm.R'] or gn[g.group].endswith('.R') and any(a in gn[g.group] for a in ['thumb','index','middle','ring','pinky']) for g in v.groups)],int);region=set(handids.tolist());finger_names=[p.name for p in r.pose.bones if p.name.endswith('.R') and any(a in p.name for a in ['thumb','index','middle','ring','pinky'])];finger_basis={n:np.array(r.pose.bones[n].matrix_basis) for n in finger_names};focusids=np.array([v.index for v in body.data.vertices if sum(g.weight for g in v.groups if gn[g.group] in finger_names+['hand.R'])>.5],int);cam=s.camera;cam0=(cam.location.copy(),cam.rotation_euler.copy(),cam.data.type,cam.data.ortho_scale);changes=[(s.render,'engine','CYCLES'),(s.cycles,'device','CPU'),(s.cycles,'samples',8),(s.cycles,'seed',0),(s.cycles,'use_animated_seed',False),(s.cycles,'use_denoising',False),(s.render,'threads_mode','FIXED'),(s.render,'threads',2),(s.render,'resolution_x',512),(s.render,'resolution_y',512),(s.render,'resolution_percentage',100),(s.render.image_settings,'file_format','PNG'),(s.render.image_settings,'color_mode','RGBA'),(s.render.image_settings,'color_depth','8'),(s.render,'filepath','')];saved=[(o,k,getattr(o,k)) for o,k,_ in changes]
for o,k,v in changes:setattr(o,k,v)
cam.data.type='ORTHO';cam.data.ortho_scale=.24;direction=Vector((.6,-1,0)).normalized();cam.rotation_euler=(-direction).to_track_quat('-Z','Y').to_euler();lane=ReactionLane();lane.on('YURI_R4_SOCIAL_GREETING_WAVE_BODY_R1');rows=[];ledger=[];folder=O/'RIGHT_HAND_CLOSE';folder.mkdir()
for f in range(1,92):
 s.frame_set(f);bpy.context.view_layer.update();data={n:geom(bpy.data.objects[n]) for n in mesh_names};assert {n:hashlib.sha256(z[0].tobytes()).hexdigest() for n,z in data.items()}==previous['rows_private'][f-1]['actual_mesh_SHA_private'];newcounts=previous['rows_private'][f-1]['new_pair_count_by_surface'];wrist=(r.matrix_world@r.pose.bones['hand.R'].matrix).translation;cam.data.ortho_scale=.19;cam.location=Vector(previous['rows_private'][f-1]['camera_location_private']);bpy.context.view_layer.update();oldpp=np.array([list(world_to_camera_view(s,cam,Vector(data[body.name][0][i]))) for i in focusids]);oldcrop=int(((oldpp[:,0]<0)|(oldpp[:,0]>1)|(oldpp[:,1]<0)|(oldpp[:,1]>1)).sum());cam.data.ortho_scale=.24;fv=data[body.name][0][focusids];target=Vector((fv.min(axis=0)+fv.max(axis=0))*.5);cam.location=target+direction*.8;bpy.context.view_layer.update();pp=np.array([list(world_to_camera_view(s,cam,Vector(fv0))) for fv0 in fv]);newcrop=int(((pp[:,0]<.05)|(pp[:,0]>.95)|(pp[:,1]<.05)|(pp[:,1]>.95)).sum());assert newcrop==0, ('Hand bounding crop',f,newcrop);out=folder/f'{f:04}.png';s.render.filepath=str(out);bpy.ops.render.render(write_still=True);finger_error=max(float(np.abs(np.array(r.pose.bones[n].matrix_basis)-finger_basis[n]).max()) for n in finger_names);assert finger_error==0 and all(np.isfinite(d[0]).all() for d in data.values());key=body.name+'__self_nonadjacent';rows.append({'frame':f,'file_SHA':sha(out),'actual_mesh_SHA_private':{n:hashlib.sha256(d[0].tobytes()).hexdigest() for n,d in data.items()},'new_pair_count_by_surface':newcounts,'right_arm_hand_new_pair_count':previous['rows_private'][f-1]['right_arm_hand_new_pair_count'],'original_exact512_hand_crop_count':oldcrop,'corrected_hand_crop_with5percent_margin_count':newcrop,'original_finger_local_error':finger_error,'finite':True,'wrist_world_private':list(wrist),'camera_target_private':list(target),'camera_location_private':list(cam.location)})
lane.off();cam.location,cam.rotation_euler,cam.data.type,cam.data.ortho_scale=cam0;s.render.resolution_x=960;s.render.resolution_y=920;s.render.filepath=str(O/'OFF_SOURCE_CAMERA_NEUTRAL.png');bpy.ops.render.render(write_still=True)
for o,k,v in saved:setattr(o,k,v)
assert snapshot(names)==before and sha(m['candidate'])==m['candidate_SHA'] and sha(m['source'])==m['source_SHA']
# Existing inclusive91 pair ledger is reused; no second collision sweep.
q={'source_SHA':m['source_SHA'],'unchanged_candidate_SHA':m['candidate_SHA'],'source79_OFF_signature_restored':True,'motion_changed':False,'new_candidate_created':False,'source_fps':30,'native_frames':[1,91],'inclusive_oracle':'all actual triangles weak/webbing included; shared-vertex true adjacency excluded; baselineOFF identities removed; all6 BODY/HEAD/HAIR surfaces','right_arm_region_criterion':'any original RIGHT hand/forearm/finger positive weight, no dominance threshold','rows_private':rows,'inclusive_surface_oracle_reused_SHA':sha(B/'alpha-social-wave-hand-quality-r1/WAVE_HAND_INCLUSIVE_CONTACT_PRIVATE_R1.json.gz'),'hand_framing_pass_all91':True,'old_exact512_hand_crop_peak':max(x['original_exact512_hand_crop_count'] for x in rows),'right_arm_hand_new_pair_peak':max(x['right_arm_hand_new_pair_count'] for x in rows),'camera':'evaluated hand bbox world-center translation follow, fixed rotation; fixed3quarter rotation, orthoscale.24,512pxCPU8samples; use existing fixed91body movies for body/root/foot verdict','TierP':0};(O/'WAVE_HAND_QUALITY_PRIVATE_R1.json').write_text(json.dumps(q,indent=2),encoding='utf8');print('EXISTING_WAVE_FULL91_RIGHT_HAND_QUALITY_SUPPLEMENT_COMPLETE',q['right_arm_hand_new_pair_peak'],flush=True)
