"""Seal exact stand-sit-hold-stand source-only candidate or rejected experiment."""
from pathlib import Path
import json,hashlib,zipfile
LAB=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-sit-stand-source-candidate-r1';I=B/'alpha-sit-stand-source-intake-r1';D=B/'alpha-sit-stand-source-delivery-r1';E=LAB/'evidence/sit-stand-source-r1';G=B/'o1-sit-stand-capture-completion-r1b';R=B/'alpha-sit-stand-capture-completion-r1b';IG=B/'o1-sit-stand-source-intake-r1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();js=lambda p:json.loads(Path(p).read_bytes());m=js(P/'SIT_STAND_SOURCE_PRIVATE_R1.json');s=js(E/'SIT_STAND_SOURCE_SCALAR_QA_R1.json');ui=js(D/'WHOLE_NORMAL1X_UI_R1.json');assert len(ui)==3 and all(x['ended'] and x['error'] is None and x['playbackRate']==1 and abs(x['duration']-121/30)<1e-5 for x in ui)
assert sha(m['source'])==m['source_SHA'] and sha(m['candidate'])==m['candidate_SHA'] and sha(m['library']['file'])==m['library']['sha256'] and sha(m['FBX_source'])==m['FBX_SHA'];g=js(G/'NATIVE_GUARD_RESULT.json');assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN' and all(sha(p)==v for p,v in g['inputs_after'].items());entries={}
def add(p,a):
 p=Path(p);assert p.is_file() and a not in entries;entries[a]=p
add(B/'SIT_STAND_PERSISTENT_STEP_CAUSAL_R1.json','causal/PERSISTENT_STEP_R1.json');add(B/'SIT_STAND_DONOR_TARGET_KNEE_CAUSAL_R1.json','causal/DONOR_TARGET_KNEE_R1.json');add(B/'SIT_STAND_VALID_EXISTING_CAPTURE_R1.json','preserved-first-native-capture-validation.json');add(m['source'],'source/Character_Master_NeckSkin_R4.blend');add(m['FBX_source'],'known-CC0-source/UAL1_Standard.fbx')
for folder,prefix in [(P,'candidate-native-qa'),(I,'dedicated-source-intake'),(D,'review'),(E,'public-qa'),(G,'guard-capture-completion'),(R,'completed-native-capture'),(B/'o1-sit-stand-source-candidate-r1b','preserved-first600sec-native-timeout'),(B/'o1-sit-stand-capture-completion-r1','preserved-completion-indentation-failure'),(IG,'guard-source-intake')]:
 for p in folder.rglob('*'):
  if p.is_file():add(p,prefix+'/'+p.relative_to(folder).as_posix())
for n in ['r4_sit_stand_source_intake_r1.py','r4_sit_stand_source_intake_owned_prepare_r1.py','r4_sit_stand_source_candidate_r1.py','r4_sit_stand_source_candidate_r1b.py','r4_sit_stand_source_candidate_owned_prepare_r1.py','r4_sit_stand_adapter_r1.py','r4_sit_stand_source_delivery_r1.py','r4_sit_stand_source_package_r1.py','r4_sit_stand_source_package_r1b.py','r4_sit_stand_capture_completion_r1.py','r4_sit_stand_capture_completion_r1b.py','r4_sit_stand_capture_completion_owned_prepare_r1.py','r4_sit_stand_source_delivery_r1b.py','r4_sit_stand_source_delivery_r1c.py','r4_appearance_adapter.py','r4_appearance_signature.py','r4_native_walk_source_supply_r1.py','r4_existing_reach_contact_closure_r1.py','native_preservation.py']:add(LAB/'scripts'/n,'workflow/'+n)
# Preserve unused pinned draft before native launch; only R1b collector executed, one saved candidate.
for p in (B/'o1-sit-stand-source-candidate-r1').rglob('*'):
 if p.is_file():add(p,'unused-prelaunch-draft-guard/'+p.relative_to(B/'o1-sit-stand-source-candidate-r1').as_posix())
readme=D/'SIT_STAND_SOURCE_HANDOFF_R1.md';readme.write_text("# ONE original-rig stand-sit-hold-stand source experiment\n\nImmutable R4 source visual authority / original78 full raw source OFF preserved including fresh serialized reopen, material/geometry/keys/weights/rest/drivers/camera/textures. No donor geometry into R4. Candidate defaults OFF. Append ONLY four Actions from candidate-native-qa/YURI_R4_SIT_STAND_ACTIONS_ONLY_R1.blend; never donor mesh/rig/material/image. workflow/r4_sit_stand_adapter_r1.py SitStandLane().on()/off() binds exact original hierarchy and restores previous frame/bindings/poses/carrier location. Authoring fps30; session timeline1..121, enter1..40, hold40..90, exit90..121. Set30fps only for preview session and restore original24fps before saving canonical source. Saved candidate original24fps/OFF. MP4 source-native1x121/30=4.033333s including terminal endpoint.\n\nExisting pinned CC0 Quaternius UAL1_Standard.fbx Sitting_Enter/Idle_Loop/Exit dedicated source reused. Imported donor geometry ONLY transient empty intake scene, discarded before source R4 opens. Intake private raw bone matrices identify sourceActions/fps/frames. Source world basis180deg Z; lower source anatomical rest, upper common standing neutral, target hierarchy/rest/native bone lengths retained; leglength-normalized pelvis translation, ONE actual lowest-sole floor-fit pelvisZ. Original carrier static. Fixed fitted seat-plane/pelvis anchor witness metadata and separate yellow-line QA montage do not implement a product chair or certify support/contact forces. No second source candidate/parameter family/exporter/Unity changes.\n\nFirst native job600sec WATCHDOG terminated/drained after candidate/all121data/154captures; incomplete original preserved, no strictPASS waiver. Separate exact candidate render-only completion reused154byte-exact native frames and captured209missing frames, freshrawOFF/sourcepixels validated. Initial completion indentation failure also preserved, repaired collector suffix and newguard. No second motion candidate or authoring/contact rerun. All121actual BODY/HEAD/HAIR weak-unweighted triangle identity self/cross new intersections versus sourceOFF, actual original support patch world gaps/drift and persistent-proximity step, pelvis trajectory/localquat ROM/neckheadhair transport measured. Quantitative + whole1x visual verdict is in public report; no scalar-only promotion. All121front/quarter/side native frames,3whole MP4 decode and1x UI through-end receipts. Source-camera960x920OFF decodedRGBA0. Source/canonical/R2/08caad7/C1/C2/C3 and closed packets preserved. Unity/TierP/F2/StageB/physical balance and hand/seat contact remain HOLD. Public Git only scripts/scalars/hash pointers, raw models/geometry/motion/images/video are private.\n",encoding='utf8');add(readme,'SIT_STAND_SOURCE_HANDOFF_R1.md')
idx={'source_SHA':m['source_SHA'],'FBX_SHA':m['FBX_SHA'],'candidate_SHA':m['candidate_SHA'],'library_SHA':m['library']['sha256'],'status':s['verdict'],'TierP':0,'members':[{'path':a,'bytes':p.stat().st_size,'sha256':sha(p)} for a,p in sorted(entries.items())]};ip=D/'PACKET_INDEX_R1.json';ip.write_text(json.dumps(idx,indent=2),encoding='utf8');add(ip,'PACKET_INDEX_R1.json');z=B/'YURI_R4_SIT_STAND_SOURCE_EXPERIMENT_R1_20261005.zip'
with zipfile.ZipFile(z,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as f:
 for a,p in sorted(entries.items()):f.write(p,a)
with zipfile.ZipFile(z) as f:
 assert f.testzip() is None
 for x in idx['members']:
  v=f.read(x['path']);assert len(v)==x['bytes'] and hashlib.sha256(v).hexdigest()==x['sha256']
r={'packet':str(z),'sha256':sha(z),'bytes':z.stat().st_size,'members':len(entries),'indexed_members':len(idx['members']),'CRC_SHA_size_all_verified':True,'source_SHA':m['source_SHA'],'FBX_SHA':m['FBX_SHA'],'candidate_SHA':m['candidate_SHA'],'library_SHA':m['library']['sha256'],'library_bytes':m['library']['bytes'],'closed_once':True,'status':s['verdict'],'TierP':0};(E/'PRIVATE_PACKET_RECEIPT_R1.json').write_text(json.dumps(r,indent=2),encoding='utf8');print(json.dumps(r,indent=2))
