"""Encode actual stand-sit-hold-stand and fixed seat witness metadata."""
from pathlib import Path
import json,hashlib,subprocess,math
import numpy as np
from PIL import Image,ImageDraw
LAB=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-sit-stand-source-candidate-r1';R=B/'alpha-sit-stand-capture-completion-r1b';D=B/'alpha-sit-stand-source-delivery-r1';E=LAB/'evidence/sit-stand-source-r1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();js=lambda p:json.loads(Path(p).read_bytes());m=js(P/'SIT_STAND_SOURCE_PRIVATE_R1.json');completion=js(R/'SIT_STAND_CAPTURE_COMPLETION_R1.json');m['views']=completion['views'];g=js(B/'o1-sit-stand-capture-completion-r1b/NATIVE_GUARD_RESULT.json');assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN' and g['terminal_job']['active']==0 and completion['all363_native_capture_complete'];D.mkdir(exist_ok=False);E.mkdir(exist_ok=False);movies=[]
for view in ['front','quarter','side']:
 frames=R/view;assert len(list(frames.glob('*.jpg')))==121;out=D/f'{view}_STAND_SIT_HOLD_STAND_NATIVE30FPS_1x.mp4';subprocess.run(['ffmpeg','-v','error','-framerate','30','-i',str(frames/'%04d.jpg'),'-frames:v','121','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-n',str(out)],check=True);subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(out),'-f','null','-'],check=True);q=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-of','json',str(out)]))['streams'][0];assert int(q['nb_read_frames'])==121 and q['avg_frame_rate']=='30/1';movies.append({'file':str(out),'sha256':sha(out),'bytes':out.stat().st_size,'view':view,'frames':121,'fps':30,'duration':float(q['duration']),'whole_decode':'PASS'})
 grid=Image.new('RGB',(256*8,280*16),'white');dr=ImageDraw.Draw(grid)
 for f in range(1,122):
  ii=f-1;x=ii%8*256;y=ii//8*280;grid.paste(Image.open(frames/f'{f:04}.jpg').resize((256,256)),(x,y+24));dr.text((x+3,y+3),f'{view} f{f} {(f-1)/30:.3f}s',fill='black')
 grid.save(D/f'ALL121_{view}_SOURCE_QA_R1.jpg',quality=94)
# Nine source-native timing samples across ALL phases, fixed seat witness drawn only on a separate QA montage.
frames=[1,10,20,30,40,65,90,105,121];grid=Image.new('RGB',(384*9,416*3),'white');dr=ImageDraw.Draw(grid)
for row,view in enumerate(['front','quarter','side']):
 cv=m['views'][view];rx,ry,rz=cv['rotation_euler'];Rx=np.array([[1,0,0],[0,math.cos(rx),-math.sin(rx)],[0,math.sin(rx),math.cos(rx)]]);Ry=np.array([[math.cos(ry),0,math.sin(ry)],[0,1,0],[-math.sin(ry),0,math.cos(ry)]]);Rz=np.array([[math.cos(rz),-math.sin(rz),0],[math.sin(rz),math.cos(rz),0],[0,0,1]]);R=Rz@Ry@Rx;target=np.array(cv['target']);center=np.array(m['seat_witness']['pelvis_anchor_world_m']);center[2]=m['seat_witness']['surface_plane_world_z_m'];points=[]
 for dx in [-.15,.15]:
  point=center+R[:,0]*dx;delta=point-target;points.append((192+float(delta@R[:,0])*384/cv['ortho_scale'],192-float(delta@R[:,1])*384/cv['ortho_scale']))
 for col,f in enumerate(frames):
  im=Image.open(R/view/f'{f:04}.jpg').convert('RGB');qdr=ImageDraw.Draw(im);qdr.line(points,fill=(255,210,0),width=2);qdr.text((4,4),'Fixed seat witness / NO FORCE CLAIM',fill=(255,210,0));grid.paste(im,(col*384,row*416+32));dr.text((col*384+3,row*416+3),f'{view} f{f} {(f-1)/30:.3f}s',fill='black')
grid.save(D/'STAND_SIT_HOLD_STAND_FIXED_SEAT_WITNESS_R1.jpg',quality=94)
a=np.asarray(Image.open(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png').convert('RGBA'));z=np.asarray(Image.open(R/'SIT_STAND_OFF_SOURCE_NEUTRAL_R1.png').convert('RGBA'));assert np.array_equal(a,z);pixel={'changed_pixels':0,'max_RGBA_delta':0,'exact_decoded_RGBA_equal':True,'dimensions':list(a.shape)};(D/'OFF_PIXEL_QA_R1.json').write_text(json.dumps(pixel,indent=2),encoding='utf8')
scalar={k:v for k,v in m.items() if k not in ['original78_signature_private','author_rows_private','rows_private','source','candidate','library','FBX_source']};scalar['capture_completion']=completion;scalar['initial_native_watchdog_guard_SHA']='5e4e7697392e5779d1a737dec9990c290cad62e2a62621fbe84a5184073f6462';scalar['library_SHA']=m['library']['sha256'];scalar['library_bytes']=m['library']['bytes'];scalar['OFF_pixels']=pixel;scalar['visual']='PENDING_FULL1X';scalar['verdict']='SOURCE_RETARGET_HOLD_PENDING_VISUAL_CONTACT';(E/'SIT_STAND_SOURCE_SCALAR_QA_R1.json').write_text(json.dumps(scalar,indent=2),encoding='utf8');(D/'VIDEO_CUSTODY_R1.json').write_text(json.dumps(movies,indent=2),encoding='utf8')
html='<!doctype html><meta charset="utf-8"><title>R4 stand-sit-hold-stand source motion</title><style>body{background:#222;color:#eee;font:16px system-ui}section{display:flex;gap:8px}video{width:32%}button{padding:12px;font-size:20px}</style><h1>Original R4: stand / sit / short seated hold / stand</h1><p>121frames30fps /4sec endpointspan /4.033333sec encode / native1x. Existing dedicated CC0 Sitting_Enter39steps, seated50steps, Exit31steps. ONE original-rig rest-aware normalized source retarget; no donor geometry. Fixed fitted seat anchor recorded, no product prop or physical support claim. Original source78/freshOFF/pixels preserved; Unity/TierP/F2/StageB HOLD.</p><button onclick="document.querySelectorAll(\'video\').forEach(v=>{v.currentTime=0;v.playbackRate=1;v.play()})">Play complete stand sit hold stand at native 1x</button><section>'
for x in movies:html+=f'<video controls preload="auto" src="{Path(x["file"]).name}"></video>'
html+='</section><p>First owned job reached600sec after121data/candidate and154captures; preserved watchdogFAIL/drain. SAME candidate render-only completion reused154validnative images unchanged and captured209missing frames; no retarget/contact scan rerun.</p><p>Full121frames each front/quarter/side. Floor/foot/seat/motion contact QA in scalar report; visual playback alone does not grant support/contact force. Source-native1x, no respeed.</p><img width="100%" src="STAND_SIT_HOLD_STAND_FIXED_SEAT_WITNESS_R1.jpg">';(D/'REVIEW_SIT_STAND_SOURCE_R1.html').write_text(html,encoding='utf8');print(json.dumps({k:scalar[k] for k in ['candidate_SHA','library_SHA','seat_witness','feet','all121_new_surface_pair_peak','max_body_step_m','pelvis_stand_to_seat_delta_m','seated_pelvis_anchor_max_distance_m']},indent=2))
