"""Existing Wave missing RIGHT finger/webbing QA only: unchanged action, inclusive surface and full close view."""
import bpy,sys,json,hashlib,ast,gzip
from pathlib import Path
import numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
from r4_appearance_adapter import ReactionLane
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-social-wave-hand-quality-r1';O.mkdir(exist_ok=False);L=H.parent;m=json.loads((L/'evidence/alpha-social-greeting-source-candidate-r1/SOCIAL_GREETING_MANIFEST_R1.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(m['source'])==m['source_SHA'] and sha(m['candidate'])==m['candidate_SHA'];bpy.ops.wm.open_mainfile(filepath=m['candidate'],use_scripts=False);s=bpy.context.scene;r=bpy.data.objects['Meshy_Fitted_Rig'];body=bpy.data.objects['Meshy_Body_NeutralCovered'];names=list(bpy.data.actions.keys());before=snapshot(names)
for fn,defs in [('r4_native_walk_source_supply_r1.py',['contact']),('r4_existing_reach_contact_closure_r1.py',['geom'])]:
 tree=ast.parse((H/fn).read_text(encoding='utf8'));exec(compile(ast.Module(body=[x for x in tree.body if isinstance(x,ast.FunctionDef) and x.name in defs],type_ignores=[]),'<same_inclusive_actual_surface>','exec'))
fixed={};mesh_names=['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4'];neutral={n:geom(bpy.data.objects[n]) for n in mesh_names};base,_=contact(neutral);gn={g.index:g.name for g in body.vertex_groups};handids=np.array([v.index for v in body.data.vertices if any(gn[g.group] in ['hand.R','forearm.R'] or gn[g.group].endswith('.R') and any(a in gn[g.group] for a in ['thumb','index','middle','ring','pinky']) for g in v.groups)],int);region=set(handids.tolist());finger_names=[p.name for p in r.pose.bones if p.name.endswith('.R') and any(a in p.name for a in ['thumb','index','middle','ring','pinky'])];finger_basis={n:np.array(r.pose.bones[n].matrix_basis) for n in finger_names};cam=s.camera;cam0=(cam.location.copy(),cam.rotation_euler.copy(),cam.data.type,cam.data.ortho_scale);changes=[(s.render,'engine','CYCLES'),(s.cycles,'device','CPU'),(s.cycles,'samples',8),(s.cycles,'seed',0),(s.cycles,'use_animated_seed',False),(s.cycles,'use_denoising',False),(s.render,'threads_mode','FIXED'),(s.render,'threads',2),(s.render,'resolution_x',512),(s.render,'resolution_y',512),(s.render,'resolution_percentage',100),(s.render.image_settings,'file_format','PNG'),(s.render.image_settings,'color_mode','RGBA'),(s.render.image_settings,'color_depth','8'),(s.render,'filepath','')];saved=[(o,k,getattr(o,k)) for o,k,_ in changes]
for o,k,v in changes:setattr(o,k,v)
cam.data.type='ORTHO';cam.data.ortho_scale=.19;direction=Vector((.6,-1,0)).normalized();cam.rotation_euler=(-direction).to_track_quat('-Z','Y').to_euler();lane=ReactionLane();lane.on('YURI_R4_SOCIAL_GREETING_WAVE_BODY_R1');rows=[];ledger=[];folder=O/'RIGHT_HAND_CLOSE';folder.mkdir()
for f in range(1,92):
 s.frame_set(f);bpy.context.view_layer.update();data={n:geom(bpy.data.objects[n]) for n in mesh_names};ps,_=contact(data);new={k:ps[k]-base[k] for k in ps};wrist=(r.matrix_world@r.pose.bones['hand.R'].matrix).translation;target=wrist+Vector((0,0,.035));cam.location=target+direction*.8;out=folder/f'{f:04}.png';s.render.filepath=str(out);bpy.ops.render.render(write_still=True);finger_error=max(float(np.abs(np.array(r.pose.bones[n].matrix_basis)-finger_basis[n]).max()) for n in finger_names);assert finger_error==0 and all(np.isfinite(d[0]).all() for d in data.values());key=body.name+'__self_nonadjacent';handnew={p for p in new[key] if any(i in region for t in p for i in t)};rows.append({'frame':f,'file_SHA':sha(out),'actual_mesh_SHA_private':{n:hashlib.sha256(d[0].tobytes()).hexdigest() for n,d in data.items()},'new_pair_count_by_surface':{k:len(v) for k,v in new.items()},'right_arm_hand_new_pair_count':len(handnew),'original_finger_local_error':finger_error,'finite':True,'wrist_world_private':list(wrist),'camera_target_private':list(target),'camera_location_private':list(cam.location)});ledger.append({'frame':f,'new_pair_identities':{k:sorted(v) for k,v in new.items()},'right_arm_hand_new_pair_identities':sorted(handnew)})
lane.off();cam.location,cam.rotation_euler,cam.data.type,cam.data.ortho_scale=cam0;s.render.resolution_x=960;s.render.resolution_y=920;s.render.filepath=str(O/'OFF_SOURCE_CAMERA_NEUTRAL.png');bpy.ops.render.render(write_still=True)
for o,k,v in saved:setattr(o,k,v)
assert snapshot(names)==before and sha(m['candidate'])==m['candidate_SHA'] and sha(m['source'])==m['source_SHA']
with gzip.open(O/'WAVE_HAND_INCLUSIVE_CONTACT_PRIVATE_R1.json.gz','wt',encoding='utf8') as ff:json.dump(ledger,ff)
q={'source_SHA':m['source_SHA'],'unchanged_candidate_SHA':m['candidate_SHA'],'source79_OFF_signature_restored':True,'motion_changed':False,'new_candidate_created':False,'source_fps':30,'native_frames':[1,91],'inclusive_oracle':'all actual triangles weak/webbing included; shared-vertex true adjacency excluded; baselineOFF identities removed; all6 BODY/HEAD/HAIR surfaces','right_arm_region_criterion':'any original RIGHT hand/forearm/finger positive weight, no dominance threshold','rows_private':rows,'right_arm_hand_new_pair_peak':max(x['right_arm_hand_new_pair_count'] for x in rows),'camera':'world wrist translation follow with constant world offset; fixed3quarter rotation, orthoscale.19,512pxCPU8samples; use existing fixed91body movies for body/root/foot verdict','TierP':0};(O/'WAVE_HAND_QUALITY_PRIVATE_R1.json').write_text(json.dumps(q,indent=2),encoding='utf8');print('EXISTING_WAVE_FULL91_RIGHT_HAND_QUALITY_SUPPLEMENT_COMPLETE',q['right_arm_hand_new_pair_peak'],flush=True)
