"""Read ONLY dedicated known CC0 seated source, never mix donor geometry into R4."""
import bpy,sys,json,hashlib
from pathlib import Path
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-sit-stand-source-intake-r1';O.mkdir(exist_ok=False)
short=Path('C:/Users/JAEWAN/.codex/worktrees/common-motion-curation-r1/yuri-room-mvp/common-motion-r1/manifests/YURI_COMMON_MOTION_CHARACTER_SHORTLIST_R1.json');manifest=json.loads(short.read_bytes());items=[x for x in manifest['motions'] if x['display_name'] in ['Sitting_Enter','Sitting_Idle_Loop','Sitting_Exit']];assert len(items)==3;src=Path(items[0]['source_path']);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(src)==items[0]['file_hash'];P=Path('C:/Users/JAEWAN/scratch/YURI_COMMON_MOTION_CURATION_R1/provisional-first4-r1/target-reference/Character_Master_NeckSkin_R4.blend');assert sha(P)=='a30fc513a6da3782742c337ee4a50ab3523b82467517d91d84eb0cc0ede2aafa'
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.fbx(filepath=str(src),use_anim=True,ignore_leaf_bones=False,automatic_bone_orientation=False);rigs=[o for o in bpy.data.objects if o.type=='ARMATURE'];print('SITTING_IMPORTED_RIGS',[(o.name,len(o.pose.bones)) for o in rigs],flush=True);print('SITTING_IMPORTED_ACTIONS',[a.name for a in bpy.data.actions],flush=True);assert len(rigs)==1;r=rigs[0];rest={b.name:(r.matrix_world@b.matrix_local).to_4x4() for b in r.data.bones};samples={};acts={}
for tag in ['Sitting_Enter','Sitting_Idle_Loop','Sitting_Exit']:
 matches=[a for a in bpy.data.actions if tag in a.name];assert len(matches)==1,(tag,[a.name for a in matches]);a=matches[0];r.animation_data_create().action=a;r.animation_data.action_slot=a.slots[0];fc=[f for l in a.layers for st in l.strips for bag in st.channelbags for f in bag.fcurves];ts=sorted({float(k.co.x) for f in fc for k in f.keyframe_points});lo=int(round(min(ts)));hi=int(round(max(ts)));rows=[]
 for f in range(lo,hi+1):
  bpy.context.scene.frame_set(f);bpy.context.view_layer.update();rows.append({b.name:[list(x) for x in r.matrix_world@b.matrix] for b in r.pose.bones})
 samples[tag]=rows;acts[tag]={'imported_action':a.name,'frame_range':[lo,hi],'fps':bpy.context.scene.render.fps/bpy.context.scene.render.fps_base,'curves':len(fc),'frames':len(rows),'source_duration_from_shortlist_seconds':next(x['source_duration_sec'] for x in items if x['display_name']==tag)}
rest={n:[list(x) for x in v] for n,v in rest.items()};bones={b.name:{'parent':b.parent.name if b.parent else None,'length_world':float((r.matrix_world@b.tail_local-r.matrix_world@b.head_local).length)} for b in r.data.bones}
bpy.ops.wm.open_mainfile(filepath=str(P),use_scripts=False);names=list(bpy.data.actions.keys());before=snapshot(names);native_seat=[n for n in names if any(t in n.lower() for t in ['sit','seat','standup','stand_up'])];assert snapshot(names)==before
meta={'source':str(P),'source_SHA':sha(P),'shortlist_SHA':sha(short),'FBX_source':str(src),'FBX_SHA':sha(src),'license':'CC0-1.0 per existing pinned shortlist','source_action_intake':acts,'bones':bones,'rest_world_private':rest,'samples_private':samples,'native_R4_dedicated_sitting_actions':native_seat,'source_original78_preserved':len(names)==78,'donor_geometry_into_R4':False,'saved_candidate':False};(O/'SIT_STAND_SOURCE_INTAKE_PRIVATE_R1.json').write_text(json.dumps(meta,indent=2),encoding='utf8');print('SIT_STAND_INTAKE_COMPLETE',acts,native_seat,flush=True)
