"""Same immutable Wave motion: full91 native1x hand-framing A/B, no motion correction claim."""
from pathlib import Path
import json,hashlib,subprocess
from PIL import Image,ImageDraw
import numpy as np
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-social-wave-hand-quality-delivery-r1';O.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();movies=[];source=[]
def verify(p):
 subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(p),'-f','null','-'],check=True);st=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-of','json',str(p)]))['streams'][0];assert int(st['nb_read_frames'])==91 and st['avg_frame_rate']=='30/1';return {'path':str(p),'SHA':sha(p),'frames':91,'fps':30,'duration':float(st['duration']),'whole_decode':'PASS'}
for v in ['r1','r2']:
 R=B/f'alpha-social-wave-hand-quality-{v}';G=B/f'o1-social-wave-hand-quality-{v}/NATIVE_GUARD_RESULT.json';assert json.loads(G.read_bytes())['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN';m=json.loads((R/'WAVE_HAND_QUALITY_PRIVATE_R1.json').read_bytes());assert len(m['rows_private'])==91 and m['unchanged_candidate_SHA']=='580b80181a400b7eaae2f6418f7bb550dcccba6fc88fdde84860958adbff9c44'
 for row in m['rows_private']:assert sha(R/'RIGHT_HAND_CLOSE'/f'{row["frame"]:04}.png')==row['file_SHA']
 baseline=np.array(Image.open(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png').convert('RGBA'));assert np.array_equal(baseline,np.array(Image.open(R/'OFF_SOURCE_CAMERA_NEUTRAL.png').convert('RGBA')))
 out=O/f'RIGHT_HAND_{v.upper()}_FULL91_NATIVE30_1x.mp4';subprocess.run(['ffmpeg','-v','error','-framerate','30','-i',str(R/'RIGHT_HAND_CLOSE/%04d.png'),'-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-n',str(out)],check=True);movies.append(verify(out));source.append({'version':v,'unchanged_candidate_SHA':m['unchanged_candidate_SHA'],'guard_SHA':sha(G),'OFF_RGBA_difference':0,'motion_changed':False})
pair=O/'RIGHT_HAND_CAMERA_R1_LEFT_R2_RIGHT_FULL91_NATIVE1x.mp4';subprocess.run(['ffmpeg','-v','error','-i',movies[0]['path'],'-i',movies[1]['path'],'-filter_complex','[0:v][1:v]hstack=inputs=2[v]','-map','[v]','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-filter_complex_threads','1','-n',str(pair)],check=True);movies.append(verify(pair))
for f in [1,23,41,45,75,91]:
 grid=Image.new('RGB',(1024,538),'white');dr=ImageDraw.Draw(grid)
 for i,v in enumerate(['r1','r2']):grid.paste(Image.open(B/f'alpha-social-wave-hand-quality-{v}/RIGHT_HAND_CLOSE/{f:04}.png').convert('RGB'),(i*512,26));dr.text((i*512+6,5),f'f{f} {v.upper()} CAMERA ONLY same unchanged Wave30fps',fill='black')
 grid.save(O/f'CAMERA_QUALITY_AB_f{f}.jpg',quality=96)
(O/'HAND_VIDEO_CUSTODY_R1.json').write_text(json.dumps({'existing_Wave_packet_SHA':'f1621cc214e09d3c8ddcd020b4e167d8ca739c31687c80f7ab11654e73c883fd','motion_changed':False,'new_candidate_created':False,'source':source,'movies':movies},indent=2),encoding='utf8')
html='<!doctype html><meta charset="utf-8"><title>Existing R4 Wave hand quality</title><style>body{background:#222;color:#eee;font:16px system-ui;margin:20px}video{width:100%;max-width:1024px}button{padding:12px;font-size:18px}</style><h1>Existing Wave · RIGHT hand quality · camera-only A/B</h1><p>LEFT R1 wrist-offset crop / RIGHT R2 full-hand bbox framing. Same unchanged Wave candidate580b8018, all91frames native30fps,3.033333sec. Fixed3quarter camera rotation; translation/scale intentionally differ. Motion, finger pose, materials, drivers and immutable R4 preserved. No new animation, exporter or packet.</p><p>R2 actual hand vertices stay inside5% image margin at every frame. R1 clips fingertips during neutral/return. Inclusive source surface remains HOLD: BODY elbow/upperarm contacts peak59; inspected first23/peak41 pairs dominated forearm.R/upper_arm.R, not a finger-only failure. Static fingers and neutral face remain; no acting/facial/physics/Unity/F2/TierP acceptance.</p><button onclick="document.querySelector(\'video\').currentTime=0;document.querySelector(\'video\').playbackRate=1;document.querySelector(\'video\').play()">Play full91 frames at native1x</button><video controls preload="auto" src="'+pair.name+'"></video>'
(O/'REVIEW_EXISTING_WAVE_HAND_QUALITY_R1.html').write_text(html,encoding='utf8');print('EXISTING_WAVE_HAND_CAMERA_ONLY_FULL91_NATIVE1X_DECODE_OFF0')
