"""Fallback delivery QA of ONE existing native Talk asset: no new animation, export or transfer."""
from pathlib import Path
import json,hashlib,zipfile,subprocess
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');L=Path(__file__).resolve().parents[1];E=L/'evidence/tour472-wrist-w1';E.mkdir(exist_ok=True);O=B/'alpha-tour472-native-talk-supply-r1';O.mkdir(exist_ok=False);P=L/'evidence/alpha-native-talk-source-r1';receipt=json.loads((P/'PRIVATE_PACKET_RECEIPT_R1.json').read_bytes());lib=json.loads((P/'ACTION_ONLY_CUSTODY_R1.json').read_bytes());manifest=json.loads((P/'NATIVE_TALK_SOURCE_MANIFEST_R1.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();zpath=Path(receipt['file']);assert sha(zpath)==receipt['SHA'] and sha(lib['file'])==lib['SHA'];assert sha(manifest['candidate'])==manifest['candidate_SHA'] and sha(manifest['source'])==manifest['source_SHA']
with zipfile.ZipFile(zpath) as z:
 assert z.testzip() is None;index=json.loads(z.read('MEMBER_SHA256_INDEX_R1.json'));assert len(z.namelist())==85 and len(index)==84
 for n,r in index.items():data=z.read(n);assert len(data)==r['bytes'] and hashlib.sha256(data).hexdigest()==r['SHA']
 videos=[]
 for n in ['fullbody_front_NATIVE_TALK_1x.mp4','waist_3q_NATIVE_TALK_1x.mp4']:
  p=B/'alpha-native-talk-delivery-r1'/n;assert sha(p)==index['review/'+n]['SHA'];subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(p),'-f','null','-'],check=True);v=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-of','json',str(p)]))['streams'][0];assert int(v['nb_read_frames'])==121 and v['avg_frame_rate']=='24/1';videos.append({'path':str(p),'SHA':sha(p),'whole_decode':'PASS','frames':121,'fps':24,'duration':float(v['duration'])})
q={'selected_fallback':'MESHY_R2_BODY_TalkGesture native upper body, original84curves copied exactly in existing closed asset','existing_packet':receipt,'fresh_all85_CRC_all84_member_SHA_size':'PASS','existing_library':lib,'existing_source_QA_reused':'Original closed all121 grounded/lower/root/finger/OFF/scopedarm surface evidence; no fresh Blender reauthoring or export','source_SHA':manifest['source_SHA'],'source_Action_SHA':manifest['source_action_SHA'],'new_animation_candidate':False,'duplicate_transfer':False,'fresh_videos_whole_decode':videos,'Root_previous_Laptop_receiver_custody':'Root reported library1042654bytes/eae83ac3 independently verified; not freshly inspected by this worker','visual':'REFERENCE body-only; no face/acting/physics/TierP/F2/Unity acceptance','TierP':0}
(O/'NATIVE_TALK_FALLBACK_SUPPLY_REVALIDATION_R1.json').write_text(json.dumps(q,indent=2),encoding='utf8');(E/'NATIVE_TALK_FALLBACK_SUPPLY_REVALIDATION_R1.json').write_text(json.dumps(q,indent=2),encoding='utf8');print('EXISTING_NATIVE_TALK_PACKET85_CRC_SHA_SIZE_TWO121_FRAME_WHOLE_DECODE_PASS_NO_NEW_EXPORT')
