"""Readonly original left-wrist source divergence intake; reuse existing all-frame contact ledger."""
import bpy,sys,json,gzip,hashlib,math,ast,collections
from pathlib import Path
import numpy as np
from mathutils import Vector
H=Path(__file__).resolve().parent;sys.path.insert(0,str(H))
from r4_appearance_signature import snapshot,props
from r4_native_tour_adapter_r1 import NativeTourLane,ACTIONS
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');O=B/'alpha-tour472-wrist-intake-r1';O.mkdir(exist_ok=False);m=json.loads((B/'alpha-native-tour-recovery-r2/NATIVE_TOUR_RECOVERY_PRIVATE_R2.json').read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(m['candidate'])==m['candidate_SHA'] and sha(m['source'])==m['source_SHA'];bpy.ops.wm.open_mainfile(filepath=m['candidate'],use_scripts=False)
s=bpy.context.scene;r=bpy.data.objects['Meshy_Fitted_Rig'];body=bpy.data.objects['Meshy_Body_NeutralCovered'];names=list(bpy.data.actions.keys());before=snapshot(names);assert len(names)==81
ns={'bpy':bpy,'np':np,'fixed':{}};tree=ast.parse((H/'r4_existing_reach_contact_closure_r1.py').read_text(encoding='utf8'));exec(compile(ast.Module(body=[x for x in tree.body if isinstance(x,ast.FunctionDef) and x.name=='geom'],type_ignores=[]),'<same_geom>','exec'),ns);geom=ns['geom'];v0=geom(body)[0];restwrist=np.array((r.matrix_world@r.data.bones['hand.L'].matrix_local).translation);region=set(np.where(np.linalg.norm(v0-restwrist,axis=1)<.065)[0].tolist());gn={g.index:g.name for g in body.vertex_groups};ledger=json.loads(gzip.open(B/'alpha-native-tour-source-r4/NATIVE_TOUR_SURFACE_IDENTITIES_PRIVATE_R1.json.gz','rt',encoding='utf8').read());bodykey=body.name+'__self_nonadjacent';pairs=[]
for row in ledger['frames'][399:577]:
 pp=[pair for pair in row['new_pair_identities'][bodykey] if all(i in region for tri in pair for i in tri)];pairs.append({'frame':row['frame'],'left_wrist_new_pair_count':len(pp),'left_wrist_pairs_private':pp})
rest={n:{'parent':r.data.bones[n].parent.name,'head_private':list(r.data.bones[n].head_local),'tail_private':list(r.data.bones[n].tail_local),'matrix_local_private':[list(z) for z in r.data.bones[n].matrix_local],'constraints':[(c.name,c.type,props(c)) for c in r.pose.bones[n].constraints]} for n in ['hand.L','forearm.L','hand.R','forearm.R']};ln=NativeTourLane();ln.on();rows=[]
for f in range(400,578):
 s.frame_set(f);bpy.context.view_layer.update();rows.append({'frame':f,'joints_private':{n:{'quaternion':list(r.pose.bones[n].rotation_quaternion),'EulerXYZ_degrees':[a*180/math.pi for a in r.pose.bones[n].rotation_quaternion.to_euler('XYZ')],'location':list(r.pose.bones[n].location),'scale':list(r.pose.bones[n].scale),'world_head':list((r.matrix_world@r.pose.bones[n].matrix).translation)} for n in rest}})
witness=[]
for f in [432,450,460,471,472,484,500,528]:
 s.frame_set(f);bpy.context.view_layer.update();data={n:geom(bpy.data.objects[n])[0] for n in ['Meshy_Body_NeutralCovered','Character_Body_Head','Hair_Replacement_R4']};assert {n:hashlib.sha256(v.tobytes()).hexdigest() for n,v in data.items()}==m['all_rows_private'][f-1]['actual_mesh_hash_private'];witness.append({'frame':f,'actual_all_three_mesh_matches_original_ledger':True})
ln.off();assert snapshot(names)==before and sha(m['candidate'])==m['candidate_SHA'];chosen=next(x for x in pairs if x['frame']==472)['left_wrist_pairs_private'];ids=sorted({i for p in chosen for tri in p for i in tri});weights={str(i):{gn[g.group]:g.weight for g in body.data.vertices[i].groups} for i in ids};a=bpy.data.actions[ACTIONS[r.name]];source=bpy.data.actions['MESHY_R2_BODY_Tour'];curves=lambda ac:[f for l in ac.layers for st in l.strips for ba in st.channelbags for f in ba.fcurves];curve_delta=max(abs(f.evaluate(t)-next(z for z in curves(source) if z.data_path==f.data_path and z.array_index==f.array_index).evaluate(t)) for f in curves(a) if any(n in f.data_path for n in ['hand.L','forearm.L']) for t in range(400,578));assert curve_delta==0
(O/'TOUR472_WRIST_INTAKE_PRIVATE_R1.json').write_text(json.dumps({'source_SHA':m['source_SHA'],'source_Action_SHA':m['source_Action_SHA'],'native_candidate_SHA':m['candidate_SHA'],'source81_OFF_restored':True,'candidate_created':False,'original_vs_native_wrist_curve_max_error':curve_delta,'region_OFF_radius_m':.065,'region_vertex_ids_private':sorted(region),'rest_constraints_private':rest,'source_modifiers_private':[props(x) for x in body.modifiers],'rows_private':rows,'contact_rows_private':pairs,'f472_region_weights_private':weights,'actual_geometry_witness':witness},indent=2),encoding='utf8');print('TOUR472_LEFT_WRIST_READONLY_INTAKE_COMPLETE',len(chosen),'PAIRS472',flush=True)
