"""Public scalar/pointer closure for ONE local elbow candidate; arrays stay private."""
from pathlib import Path
import json,hashlib
B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');L=Path(__file__).resolve().parents[1];E=L/'evidence/tour302-elbow-c1';E.mkdir(exist_ok=True)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();m=json.loads((B/'alpha-tour302-elbow-c1d/TOUR302_ELBOW_C1_PRIVATE.json').read_bytes());rows=m['local_rows_private']
keep=['source_SHA','source_Action_SHA','parent_candidate_SHA','candidate','candidate_SHA','candidate_bytes','corrective_action','clock','fps','changed_key_frames','local_QA_frames','gesture_zero_boundaries','source_peak_hinge_degrees','candidate_peak_hinge_degrees','hinge_scale','only_forearmL_EulerZ_changed','outside_key_handles_exact','other_body_curves_exact','introduced_new_pair_identity_peaks','support_patch_component_error_m','angular_velocity_jump_gate','scoped_local_QA_pass','whole_Tour_source_acceptance','TierP']
q={k:m[k] for k in keep};q['original_velocity']={k:v for k,v in m['original_velocity'].items() if 'private' not in k};q['candidate_velocity']={k:v for k,v in m['candidate_velocity'].items() if 'private' not in k};q['local_rows_scalar']=[{k:v for k,v in x.items() if 'private' not in k} for x in rows];q['first_local_failure']={k:v for k,v in (m['first_local_failure'] or {}).items() if 'private' not in k}
q['f302_first7_removed']=next(x for x in rows if x['frame']==302)['original_first7_remaining']==0;q['BODY_peak_original']=max(x['original_BODY_new_vs_OFF'] for x in rows);q['BODY_peak_candidate']=max(x['BODY_new_vs_OFF'] for x in rows);q['counts_increased_vs_original']=any(x['BODY_new_vs_OFF']>x['original_BODY_new_vs_OFF'] for x in rows);q['source_packet_created']=False;q['Unity_F2_StageB']='UNTESTED'
q['guard_receipts']=[]
for n in ['intake-r1','elbow-c1','elbow-c1b','elbow-c1c','elbow-c1d','capture-front-r1','capture-quarter-r1','residual-localize-r1']:
 p=B/f'o1-tour302-{n}/NATIVE_GUARD_RESULT.json';g=json.loads(p.read_bytes());q['guard_receipts'].append({'name':n,'status':g['guard_status'],'SHA':sha(p),'error':g.get('error'),'wall_seconds':g.get('wall_seconds'),'path':str(p)})
res=json.loads((B/'alpha-tour302-residual-localize-r1/RESIDUAL_SURFACE_OWNERSHIP_PRIVATE_R1.json').read_bytes())
q['residual_first_frame']=303;q['residual_original_dominant_bones']=[x['dominant_original_bones'] for x in res['residual_original_weights_private']];q['residual_pair_vertex_component_error_m']=res['source_to_corrected_pair_vertex_component_error_m'];q['wrist472_actual_all_three_mesh_SHA_same_original']=res['wrist472_actual_all_three_mesh_SHA_same_original'];q['next_one_joint_direction']='Unexecuted: preserve original low-flexion keys, use continuous soft cap for forearm.L only to reduce source-pose deviation while retaining elbow-pair removal. Unchanged clavicle/neck pair remains HOLD; no further amplitude-only attempt to fix an unaffected pair.'
paths=[B/'alpha-tour302-residual-localize-r1/RESIDUAL_SURFACE_OWNERSHIP_PRIVATE_R1.json',B/'alpha-tour302-elbow-c1d/TOUR302_ELBOW_C1_PRIVATE.json',B/'alpha-tour302-elbow-c1d/LOCAL_SURFACE_IDENTITIES_PRIVATE_C1.json.gz',B/'alpha-tour302-delivery-r1/VIDEO_CUSTODY_R1.json',B/'alpha-tour302-delivery-r1/WHOLE_NORMAL1X_UI_R1.json',B/'alpha-tour302-delivery-r1/WHOLE_NORMAL1X_UI_R1.png']
q['private_custody']=[{'path':str(p),'SHA':sha(p),'bytes':p.stat().st_size} for p in paths]
(E/'TOUR302_LOCAL_SCALAR_QA_C1.json').write_text(json.dumps(q,indent=2),encoding='utf8')
(E/'VIDEO_CUSTODY_C1.json').write_bytes((B/'alpha-tour302-delivery-r1/VIDEO_CUSTODY_R1.json').read_bytes());print('TOUR302_SINGLE_CANDIDATE_SCALAR_CLOSURE_PUBLISHED')
