"""Offline original-vs-one-candidate normal-speed proof; no native rerun."""
from pathlib import Path
import json,hashlib,subprocess
import numpy as np
from PIL import Image,ImageDraw
LAB=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-walk-root-contact-c1';W=B/'alpha-native-walk-source-r1';D=B/'alpha-walk-root-contact-delivery-c1';E=LAB/'evidence/walk-root-contact-c1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();js=lambda p:json.loads(Path(p).read_bytes());m=js(P/'WALK_ROOT_CONTACT_PRIVATE_C1.json');g=js(B/'o1-walk-root-contact-c1/NATIVE_GUARD_RESULT.json');assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN' and g['terminal_job']['active']==0 and m['matched_all97_three_views_complete'];D.mkdir(exist_ok=False);E.mkdir(exist_ok=False)
a=np.asarray(Image.open(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png').convert('RGBA'));z=np.asarray(Image.open(P/'ROOT_CONTACT_OFF_SOURCE_NEUTRAL_C1.png').convert('RGBA'));assert np.array_equal(a,z);pixel={'changed_pixels':0,'max_RGBA_delta':0,'exact_decoded_RGBA_equal':True,'dimensions':list(a.shape)};(D/'OFF_PIXEL_QA_C1.json').write_text(json.dumps(pixel,indent=2),encoding='utf8')
movies=[]
for view in ['front','quarter','side']:
 assert len(list((P/view).glob('*.jpg')))==97
 candidate=D/f'{view}_ROOT_CONTACT_C1_NATIVE24FPS_1x.mp4';subprocess.run(['ffmpeg','-v','error','-framerate','24','-i',str(P/view/'%04d.jpg'),'-frames:v','97','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-n',str(candidate)],check=True)
 source=B/'alpha-native-walk-delivery-r1'/f'{view}_NATIVE_WALK_FULL97_1x.mp4';comparison=D/f'{view}_ORIGINAL_LEFT_ROOT_C1_RIGHT_NATIVE24FPS_1x.mp4';subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(source),'-threads','2','-i',str(candidate),'-filter_complex','[0:v][1:v]hstack=inputs=2[v]','-map','[v]','-frames:v','97','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-filter_complex_threads','2','-n',str(comparison)],check=True)
 for p in [candidate,comparison]:
  subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(p),'-f','null','-'],check=True);q=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-of','json',str(p)]))['streams'][0];assert int(q['nb_read_frames'])==97 and q['avg_frame_rate']=='24/1';movies.append({'file':str(p),'sha256':sha(p),'view':view,'comparison':p==comparison,'frames':97,'fps':24,'duration':float(q['duration']),'whole_decode':'PASS'})
 grid=Image.new('RGB',(256*8,280*26),'white');dr=ImageDraw.Draw(grid)
 for role,folder in enumerate([W,P]):
  for i,f in enumerate(range(1,98)):
   x=i%8*256;y=(role*13+i//8)*280;grid.paste(Image.open(folder/view/f'{f:04}.jpg').resize((256,256)),(x,y+24));dr.text((x+3,y+4),f'{"source" if role==0 else "rootC1"} {view} f{f}',fill='black')
 grid.save(D/f'ALL97_{view}_ORIGINAL_VS_ROOT_C1.jpg',quality=94)
scalar={k:v for k,v in m.items() if k not in ['actual_rows_private','step_rows_private','source','old_candidate','candidate','library']};scalar['candidate_SHA']=m['candidate_SHA'];scalar['action_library_SHA']=m['library']['sha256'];scalar['OFF_pixels']=pixel;scalar['max_original_body_bone_local_matrix_error']=max(x['original_body_bone_local_matrix_error'] for x in m['actual_rows_private']);scalar['max_all_actual_mesh_translation_residual_m']={n:max(x['world_translation_residual_by_actual_mesh_m'][n] for x in m['actual_rows_private']) for n in m['actual_rows_private'][0]['world_translation_residual_by_actual_mesh_m']}
source=max(x['max_anchored_stance_XY_excursion_m'] for x in m['foot_summary']['original'].values());new=max(x['max_anchored_stance_XY_excursion_m'] for x in m['foot_summary']['candidate'].values());scalar['anchored_source_sole_XY_excursion_reduction_percent']=100*(1-new/source);scalar['verdict']='PARTIAL_KINEMATIC_SOLE_XY_IMPROVEMENT_OTHER_GATES_HOLD' if new<source and max(scalar['max_all_actual_mesh_translation_residual_m'].values())<.001 and scalar['max_original_body_bone_local_matrix_error']==0 else 'FAIL_HOLD_ONE_ROOT_CONTACT_TRIAL_STOP';scalar['visual']='PENDING_ACTUAL_WHOLE1X';scalar['source_stance_mask_basis']='Actual3mm source floor proximity and persistent common vertices, not support forces; original mask fixed for candidate comparison.';(E/'WALK_ROOT_CONTACT_SCALAR_QA_C1.json').write_text(json.dumps(scalar,indent=2),encoding='utf8');(D/'VIDEO_CUSTODY_C1.json').write_text(json.dumps(movies,indent=2),encoding='utf8')
html='<!doctype html><meta charset="utf-8"><title>R4 native Walk root-contact C1</title><style>body{background:#222;color:#eee;font:16px system-ui}video{width:640px;max-width:100%}button{padding:12px}</style><h1>Original left · one root-only candidate right</h1><p>Full97 original24fps1x; same pose/time/fixed camera. Source sole near-floor XY median displacement drives carrier XY; original body/ankle/knee rotations unchanged. Z unchanged. Head contact/force/COM/loop/TierP/F2 HOLD, locomotion loop requires accumulated root delta.</p><button onclick="document.querySelectorAll(\'video\').forEach(v=>{v.currentTime=0;v.playbackRate=1;v.play()})">Play all three original versus root C1 views at 1x</button>'
for x in movies:
 if x['comparison']:html+=f'<h2>{x["view"]}</h2><video controls preload="auto" src="{Path(x["file"]).name}"></video>'
(D/'REVIEW_WALK_ROOT_CONTACT_C1.html').write_text(html,encoding='utf8');print(json.dumps({'verdict':scalar['verdict'],'source_sole_excursion_m':source,'candidate_sole_excursion_m':new,'reduction_percent':scalar['anchored_source_sole_XY_excursion_reduction_percent'],'body_pose_error':scalar['max_original_body_bone_local_matrix_error'],'translation_residual':scalar['max_all_actual_mesh_translation_residual_m'],'root':m['root'],'seam':m['loop_seam']},indent=2))
