"""Seal one C3 packet without altering source/C1/C2 closed packets."""
from pathlib import Path
import json,hashlib,zipfile
LAB=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-walk-body-endpoint-c3';C2=B/'alpha-walk-root-endpoint-c2b';D=B/'alpha-walk-body-endpoint-delivery-c3';E=LAB/'evidence/walk-body-endpoint-c3';G=B/'o1-walk-body-endpoint-c3';DG=B/'o1-walk-body-endpoint-diagnostic-c3';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();js=lambda p:json.loads(Path(p).read_bytes());m=js(P/'WALK_BODY_ENDPOINT_PRIVATE_C3.json');s=js(E/'WALK_BODY_ENDPOINT_SCALAR_QA_C3.json');ui=js(D/'WHOLE_TWO_CYCLE_1X_UI_C3.json');assert len(ui)==3 and all(x['ended'] and x['error'] is None and x['playbackRate']==1 and x['duration']==8 for x in ui)
assert sha(m['source'])==m['source_SHA'] and sha(m['candidate'])==m['candidate_SHA'] and sha(m['library']['file'])==m['library']['sha256'] and sha(m['C2_candidate'])==m['C2_candidate_SHA'];g=js(G/'NATIVE_GUARD_RESULT.json');assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN' and all(sha(p)==v for p,v in g['inputs_after'].items());assert sha(B/'YURI_R4_WALK_ROOT_ENDPOINT_EXPERIMENT_C2_20261005.zip')=='2986aafb398a2626f8603ce9e953324ea9332366215e666dca3bfe10ad7aeb15'
entries={}
def add(p,a):
 p=Path(p);assert p.is_file() and a not in entries;entries[a]=p
add(m['source'],'source/Character_Master_NeckSkin_R4.blend');add(m['C2_candidate'],'original-C2/'+Path(m['C2_candidate']).name)
for n in ['YURI_R4_WALK_ROOT_ENDPOINT_ACTIONS_ONLY_C2.blend','WALK_ROOT_ENDPOINT_PRIVATE_C2.json','ROOT_ENDPOINT_AND_BODY_SEAM_PRIVATE_C2.npz']:add(C2/n,'original-C2/'+n)
for folder,prefix in [(P,'C3-native-qa'),(C2/'C2_two_cycles_native','C2-byte-exact-cached-control'),(D,'review'),(E,'public-qa'),(G,'guard-C3'),(DG,'guard-narrow-diagnostic'),(B/'alpha-walk-body-endpoint-diagnostic-c3','narrow-diagnostic')]:
 for p in folder.rglob('*'):
  if p.is_file():add(p,prefix+'/'+p.relative_to(folder).as_posix())
add(B/'alpha-walk-root-contact-c1/SOURCE_AND_CANDIDATE_SOLE_TRAJECTORIES_PRIVATE_C1.npz','frozen-source-stance/SOURCE_AND_CANDIDATE_SOLE_TRAJECTORIES_PRIVATE_C1.npz')
for n in ['r4_walk_body_endpoint_diagnostic_c3.py','r4_walk_body_endpoint_owned_prepare_c3.py','r4_walk_body_endpoint_trial_c3.py','r4_walk_body_endpoint_trial_owned_prepare_c3.py','r4_walk_body_endpoint_adapter_c3.py','r4_walk_body_endpoint_delivery_c3.py','r4_walk_body_endpoint_package_c3.py','r4_walk_root_endpoint_adapter_c2.py','r4_walk_root_contact_adapter_c1.py','r4_appearance_adapter.py','r4_appearance_signature.py','r4_existing_reach_contact_closure_r1.py','native_preservation.py']:add(LAB/'scripts'/n,'workflow/'+n)
readme=D/'C3_ANIMATION_ONLY_HANDOFF.md';readme.write_text("# ONE BODY endpoint derivative C3 trial\n\nCanonical R4 source is immutable. Original C2 prior87/source78 raw OFF preserved, fresh reopen and source camera pixels exact. Candidate defaults OFF. Append ONLY four Actions from C3-native-qa/YURI_R4_WALK_BODY_ENDPOINT_ACTIONS_ONLY_C3.blend; never objects/meshes/armatures/material/images. workflow/r4_walk_body_endpoint_adapter_c3.py WalkBodyEndpointLane().on()/off() preserves source frame/pose/binding/root transform. Source fps24, actualglobal1..193,192 unique video frames8sec; root accumulates0.420/0.840m and never resets. C2 root path remains exact. Blender Cycles mode preserved, consumer Unity/FBX serialization not tested. No new exporter or product change.\n\nOne method/candidate: ranked left thigh/shin/foot12 quaternion components, compact N4 endpoint tangent average, quaternion normalization; phase2/3/4/94/95/96 only. Other BODY channels and head/hair/root keys untouched. Quantitative/visual verdict and tradeoffs in public report, no scalar-only promotion. Actual all193 eval and frozen source stance masks; affected triangles vs ALL BODY and all BODY vs HEAD/HAIR new identity regression at7 distinct changed/boundary phases, exact unchanged geometry elsewhere. Existing head/neck/source contacts remain HOLD; no physical forces/COM/MUG/F2/TierP/Unity/StageB certificate.\n\nC2 full two-cycle front/quarter/side frames reused byte-exact, no baseline rerender/reframe; all C3 frames new matching camera CPU captures. Full three comparison movies1x played, all9movies decoded, per-cycle all96 grids. Original source and old C1/C2 packets preserved; only scripts/scalar QA/SHA pointers public Git.\n",encoding='utf8');add(readme,'C3_ANIMATION_ONLY_HANDOFF.md')
idx={'source_SHA':m['source_SHA'],'C2_candidate_SHA':m['C2_candidate_SHA'],'candidate_SHA':m['candidate_SHA'],'library_SHA':m['library']['sha256'],'status':s['verdict'],'TierP':0,'members':[{'path':a,'bytes':p.stat().st_size,'sha256':sha(p)} for a,p in sorted(entries.items())]};ip=D/'PACKET_INDEX_C3.json';ip.write_text(json.dumps(idx,indent=2),encoding='utf8');add(ip,'PACKET_INDEX_C3.json');z=B/'YURI_R4_WALK_BODY_ENDPOINT_EXPERIMENT_C3_20261005.zip'
with zipfile.ZipFile(z,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as f:
 for a,p in sorted(entries.items()):f.write(p,a)
with zipfile.ZipFile(z) as f:
 assert f.testzip() is None
 for x in idx['members']:
  v=f.read(x['path']);assert len(v)==x['bytes'] and hashlib.sha256(v).hexdigest()==x['sha256']
r={'packet':str(z),'sha256':sha(z),'bytes':z.stat().st_size,'members':len(entries),'indexed_members':len(idx['members']),'CRC_SHA_size_all_verified':True,'source_SHA':m['source_SHA'],'C2_candidate_SHA':m['C2_candidate_SHA'],'candidate_SHA':m['candidate_SHA'],'library_SHA':m['library']['sha256'],'closed_once':True,'status':s['verdict'],'TierP':0};(E/'PRIVATE_PACKET_RECEIPT_C3.json').write_text(json.dumps(r,indent=2),encoding='utf8');print(json.dumps(r,indent=2))
