"""Offline cache reframe and actual accumulated two-cycle proof; no baseline rerender."""
from pathlib import Path
import json,hashlib,subprocess,zipfile
import numpy as np
from PIL import Image,ImageDraw
LAB=Path(__file__).resolve().parents[1];B=Path('C:/Users/JAEWAN/Documents/Codex/2026-10-02/files-pasted-by-the-user-yuri/outputs');P=B/'alpha-walk-root-endpoint-c2b';C1=B/'alpha-walk-root-contact-c1';D=B/'alpha-walk-root-endpoint-delivery-c2';E=LAB/'evidence/walk-root-endpoint-c2';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();js=lambda p:json.loads(Path(p).read_bytes());m=js(P/'WALK_ROOT_ENDPOINT_PRIVATE_C2.json');g=js(B/'o1-walk-root-endpoint-c2b/NATIVE_GUARD_RESULT.json');assert g['guard_status']=='PASS_STRICT_LIVE_BARRIERS_TERMINAL_DRAIN' and g['terminal_job']['active']==0 and m['actual_two_cycle_capture_complete'];D.mkdir(exist_ok=False);E.mkdir(exist_ok=False)
oldzip=B/'YURI_R4_WALK_ROOT_CONTACT_EXPERIMENT_C1_20261005.zip';assert sha(oldzip)=='3c24596b3af58e0095f4e86168db2ff94639c190336739d06ceb3a824cf931bc'
with zipfile.ZipFile(oldzip) as z:idx=json.loads(z.read('PACKET_INDEX_C1.json'));oldhash={x['path']:x['sha256'] for x in idx['members']}
cache_receipt=[];movies=[]
for view,v in m['views'].items():
 folder=D/'C1_two_cycles_reused_control'/view;folder.mkdir(parents=True);k=v['cached_to_new_pixel_scale'];dx,dy=v['cached_to_new_center_shift_xy_pixels'];tx=160*(1-k)+dx;ty=160*(1-k)+dy
 for f in range(1,193):
  if f<=96:
   p=C1/view/f'{f:04}.jpg';assert sha(p)==oldhash[f'candidate-native-qa/{view}/{f:04}.jpg'];im=Image.open(p).convert('RGB');out=im.transform((320,320),Image.Transform.AFFINE,(1/k,0,-tx/k,0,1/k,-ty/k),resample=Image.Resampling.BICUBIC,fillcolor=im.getpixel((0,0)));out.save(folder/f'{f:04}.jpg',quality=92);cache_receipt.append({'view':view,'frame':f,'original_sha256':sha(p),'reframed_sha256':sha(folder/f'{f:04}.jpg'),'method':'Original native C1 cached ortho image, calibrated affine reframe; bicubic resampling, no fresh baseline render.'})
  else:(folder/f'{f:04}.jpg').write_bytes((P/'C1_cycle2_native'/view/f'{f:04}.jpg').read_bytes())
 outputs={}
 for role,frames in [('C1',folder),('C2',P/'C2_two_cycles_native'/view)]:
  assert len(list(frames.glob('*.jpg')))==192;out=D/f'{view}_{role}_ACCUMULATED_TWO_CYCLES_NATIVE24FPS_1x.mp4';subprocess.run(['ffmpeg','-v','error','-framerate','24','-i',str(frames/'%04d.jpg'),'-frames:v','192','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-n',str(out)],check=True);outputs[role]=out
 comparison=D/f'{view}_C1_LEFT_C2_RIGHT_TWO_CYCLES_NATIVE24FPS_1x.mp4';subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(outputs['C1']),'-threads','2','-i',str(outputs['C2']),'-filter_complex','[0:v][1:v]hstack=inputs=2[v]','-map','[v]','-frames:v','192','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-threads','2','-filter_complex_threads','2','-n',str(comparison)],check=True)
 for out in [*outputs.values(),comparison]:
  subprocess.run(['ffmpeg','-v','error','-threads','2','-i',str(out),'-f','null','-'],check=True);q=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-of','json',str(out)]))['streams'][0];assert int(q['nb_read_frames'])==192 and q['avg_frame_rate']=='24/1' and abs(float(q['duration'])-8)<1e-6;movies.append({'file':str(out),'sha256':sha(out),'view':view,'comparison':out==comparison,'frames':192,'fps':24,'duration':8,'root_accumulated':True,'whole_decode':'PASS'})
 # Four grids perview, one cycle/role each; full192 review is not a three-frame substitute.
 for role,frames in [('C1',folder),('C2',P/'C2_two_cycles_native'/view)]:
  for cyc in [0,1]:
   grid=Image.new('RGB',(256*8,280*12),'white');dr=ImageDraw.Draw(grid)
   for i in range(96):
    f=cyc*96+i+1;x=i%8*256;y=i//8*280;grid.paste(Image.open(frames/f'{f:04}.jpg').resize((256,256)),(x,y+24));dr.text((x+3,y+3),f'{role} {view} global{f} {(f-1)/24:.3f}s',fill='black')
   grid.save(D/f'ALL96_{view}_{role}_cycle{cyc+1}.jpg',quality=94)
a=np.asarray(Image.open(B/'alpha-a1-contact-qa-r3/CANDIDATE_OFF_SOURCE_CAMERA_NEUTRAL.png').convert('RGBA'));z=np.asarray(Image.open(P/'ROOT_ENDPOINT_OFF_SOURCE_NEUTRAL_C2.png').convert('RGBA'));assert np.array_equal(a,z);pixel={'changed_pixels':0,'max_RGBA_delta':0,'exact_decoded_RGBA_equal':True,'dimensions':list(a.shape)};(D/'OFF_PIXEL_QA_C2.json').write_text(json.dumps(pixel,indent=2),encoding='utf8')
scalar={k:v for k,v in m.items() if k not in ['actual_rows_private','C1_original83_signature','source','candidate','library']};scalar['library_SHA']=m['library']['sha256'];scalar['OFF_pixels']=pixel;scalar['max_body_pose_matrix_delta_vs_C1']=max(x['pose_matrix_error_vs_C1'] for x in m['actual_rows_private']);scalar['max_full_mesh_C1_plus_root_correction_residual_m']={n:max(x['world_translation_residual_vs_C1_plus_endpoint_correction_m'][n] for x in m['actual_rows_private']) for n in m['actual_rows_private'][0]['world_translation_residual_vs_C1_plus_endpoint_correction_m']};scalar['verdict']='ROOT_ENDPOINT_SEAM_WORSENING_REMOVED_NATIVE_BODY_DERIVATIVE_HOLD';scalar['visual']='PENDING_ACTUAL_TWO_CYCLE_1X';scalar['cached_control_reframe_disclosure']='C1cycle1 original96 native frames reused via calibrated ortho affine resampling; C1cycle2 and all C2frames are new native fixed wider-camera captures. Cache/native noise/resampling transition at97 not motion evidence.';(E/'WALK_ROOT_ENDPOINT_SCALAR_QA_C2.json').write_text(json.dumps(scalar,indent=2),encoding='utf8');(D/'C1_CACHE_REFRAME_CUSTODY_C2.json').write_text(json.dumps(cache_receipt,indent=2),encoding='utf8');(D/'VIDEO_CUSTODY_C2.json').write_text(json.dumps(movies,indent=2),encoding='utf8')
html='<!doctype html><meta charset="utf-8"><title>R4 C1 versus C2 accumulated two-cycle Walk</title><style>body{background:#222;color:#eee;font:16px system-ui}video{width:640px;max-width:100%}button{padding:12px}</style><h1>C1 left · root endpoint C2 right · TWO accumulated cycles</h1><p>192frames /24fps /8s /1x. Root delta accumulates0.420m then0.840m; never resets. Source body/ankle/knee pose/stance mask/rootZ unchanged. Native BODY derivative/physical support/head contact/TierP/F2 remain HOLD.</p><p>C1cycle1 reused cached native frames via disclosed calibrated orthographic reframe/bicubic resampling. C1cycle2 and all C2frames are actual new native wide fixed-camera renders. Cache-to-native texture noise differs at97; not a pose or shader repair.</p><button onclick="document.querySelectorAll(\'video\').forEach(v=>{v.currentTime=0;v.playbackRate=1;v.play()})">Play C1 versus C2 accumulated two cycles at 1x</button>'
for x in movies:
 if x['comparison']:html+=f'<h2>{x["view"]}</h2><video controls preload="auto" src="{Path(x["file"]).name}"></video>'
(D/'REVIEW_WALK_ROOT_ENDPOINT_C2.html').write_text(html,encoding='utf8');print(json.dumps({'seam':m['seam'],'root':m['root_speed'],'feet':m['feet'],'lower_bound':m['body_derivative_uniform_translation_unavoidable_max_residual_lower_bound_m_per_s'],'translation_residual':scalar['max_full_mesh_C1_plus_root_correction_residual_m']},indent=2))
